Feature: To Test EAS Portal Functionalities

  @SaveContract__USA_PGUPGRADE_1
  Scenario Outline: Add a New Contract
    Given Go to url with data as "<TestCase>" and "<Portal>" and "<Language>"and "<Dealer>"
    And Login as "<UserName>" and "<Password>" and "<Captcha>"
    When Click on add New eContract
    And Decode the VIN "<Vin>"
    And Enter contract purchase information "<Vin>" and "<Trim>" and "<Inservicedate>" and "<ContractPurchaseDate>" and "<Vehicle_Purchase>" and "<Vehicle_Purchase_Date>" and "<Vehicle_condtion>" and "<FinanceType>" and "<odometer>" and "<Province>"
    And Select product and get rates "<SelectProduct>" and "<BundleSelection>" and "<Plan>" and "<Term>" and "<TermMiles>" and "<Deductible>" and "<RetailPrice>" and "<DealerCost>" and "<FirstServiceInterval>" and "<FinalServiceInterval>" and "<RegistrationCode>"
    And Verify Dealer Cost and Retail Price "<DealerCost>" and "<RetailPrice>"
    And Enter customer details "<isThisaBussiness>" and "<customerAgreementLanguage>" and "<BussinessName>" and "<FirstName>" and "<LastName>" and "<Address>" and "<PostalCode>" and "<PhoneNumber1>" and "<EmailAddress>" and "<Co-Signer>" and "<cos-First Name>" and "<cos-Last Name>" and "<cos-Address>" and "<cos-Postal Code>" and "<cos-Phone Number 1>" and "<cos-Email Address>" and "<SelectProduct>"
    And Enter vehicle purchase price and finance info "<SelectProduct>" and "<VehicleMSRP>" and "<FinanceAmount>" and  "<APR>" and "<GrossCapCost>" and "<Vehicleprice>"
    And Select Lienholder "<Lienholder>" and "<SelectProduct>"
    And Save the contract
    And Go to the summary page
    Then Logout out from the portal

    Examples: 
      | TestCase | Portal         | Language   | Dealer   | UserName | Password | Captcha | Vin               | Make        | Model        | Trim                  | Year | Inservicedate | ContractPurchaseDate | Vehicle_Purchase | Vehicle_Purchase_Date | Vehicle_condtion | FinanceType | odometer | SelectProduct                    | BundleSelection             | Plan                                                   | Term | TermMiles | Deductible | FirstServiceInterval | FinalServiceInterval | RegistrationCode | DealerCost | RetailPrice | isThisaBussiness | BussinessName | FirstName | LastName      | Address    | PostalCode | PhoneNumber1 | EmailAddress  | Co-Signer | cos-FirstName | cos-LastName | cos-Address | cos-PostalCode | cos-PhoneNumber1 | cos-EmailAddress | VehicleMSRP | FinanceAmount | APR | GrossCapCost | Vehicleprice | Lienholder                   |
      |        1 | Volkswagen_VCI |            | VW422530 | vwqaauto | ******** |         | 1V2AP2CA4JC562612 | VOLKSWAGEN  | ATLAS        | 2.0T S                | 2018 | 01-17-2020    | 01-17-2020           | Yes              | 01-17-2020            | New              | LEASE       |       14 | VW LEASE PROTECTION              |                             | LEASE PROTECTION                                       |   48 |         0 |          0 |                      |                      |                  |        575 |         967 | No               |               | TESTQA003 | PGUPGRADE101  | 123 STREET |      30328 |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |       20000 |         15000 | 0.5 |        10000 |        25000 |                              |
      |        2 | Audi_VCI       |            | AU422A03 | auqaauto | ******** |         | WA1VCAFP5HA038612 | AUDI        | SQ5          | 3.0T QUATTRO PRESTIGE | 2017 | 01-17-2020    | 01-17-2020           | Yes              | 01-17-2020            | New              | LEASE       |      151 | AUDI LEASE PROTECTION            |                             | LEASE END PROTECTION                                   |   36 |         0 |          0 |                      |                      |                  |        590 |         574 | No               |               | TESTQA014 | PGUPGRADE102  | 123 STREET |      30328 |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |       20000 |         15000 | 0.5 |        10000 |        25000 |                              |
      |        3 | Ducati_vci     |            | DU101156 | duqaauto | ******** |         | ZDM14BPW3EB026112 | DUCATI      | PANIGALE     | 1199 S                | 2014 | 01-17-2020    | 01-17-2020           | Yes              | 01-17-2020            | New              | FINANCE     |      100 | DUCATI TIRE & WHEEL PROTECTION   |                             | TIRE & WHEEL PROTECTION                                |   24 |         0 |          0 |                      |                      |                  |        285 |         299 | No               |               | TESTQA023 | PGUPGRADE103  | 123 STREET |      30328 |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |       20000 |         15000 | 0.5 |        10000 |        25000 |                              |
      |        4 | Porsche_US     |            | PORS1820 | prqaauto | ******   |         | WP0CA2A80HS220877 | PORSCHE     | 718 BOXSTER  | BASE                  | 2017 | 05-10-2018    | 01-17-2020           | Yes              | 09/26/2018            | Pre-Owned        | FINANCE     |    18688 | QUALITYSHIELD GAP PROTECTION     |                             | GAP PROTECTION                                         |   12 | NA        |          0 |                      |                      |                  |        190 |         210 | No               |               | TESTQA031 | PGUPGRADE104  | 123 STREET |      30328 |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |       20000 |         15000 | 0.5 |        10000 |        25000 |                              |
      |        5 | Bentley_US     |            | BENT3071 | bnqaauto | ******   |         | SJAAC2ZV2HC015116 | BENTLEY     | BENTAYGA W12 | BASE                  | 2017 | 05-10-2018    | 01-17-2020           | Yes              | 09/26/2018            | New              | LEASE       |       11 | BFS LEASE-END PROTECTION         |                             | Bentley Protection Plan Lease-End Protection           |   36 | NA        |          0 |                      |                      |                  |       1840 |        1860 | No               |               | TESTQA041 | PGUPGRADE105  | 123 STREET |      30328 |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |       20000 |         15000 | 0.5 |        10000 |        25000 |                              |
      |        6 | Lamborghini_US |            | LAMB5109 | lmqaauto | ******   |         | ZHWUC1ZD4HLA05825 | LAMBORGHINI | AVENTADOR    | LP700_4               | 2017 | 05-10-2018    | 01-17-2020           | Yes              | 09/26/2018            | Pre-Owned        | FINANCE     |    18688 | LFS GAP PROTECTION               |                             | Lamborghini Protection Plan Guaranteed Auto Protection |   12 | NA        |          0 |                      |                      |                  |        560 |         580 | No               |               | TESTQA046 | PGUPGRADE106  | 123 STREET |      30328 |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |       20000 |         15000 | 0.5 |        10000 |        25000 |                              |
      |        7 | Vroom          |            | 00AA1005 | vrqaauto | ******** |         | 3VW447AU2HM033520 |             |              |                       | 2016 | 2017-06-27    | 2020-01-17           | Yes              |                       | Pre-Owned        | FINANCE     |     2000 | VROOM VSC PROTECTION             |                             | PLATINUM COVERAGE                                      |   48 |    100000 |        100 |                      |                      |                  |       1028 |        1374 | No               |               | TESTQA025 | PGUPGRADE107  | 123 STREET |      90013 |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |       10000 |         15000 | 0.5 |        10000 |        25000 |                              |
      |        8 | Fuccillo       |            | HYUNY062 | fcqaauto | ******   |         | KMHD84LF5HU066464 |             |              |                       |      | 2017-03-09    | 2020-01-17           | Yes              |                       | New              | FINANCE     |       53 | FUCCILLO PREPAID MAINTENANCE     |                             | STANDARD OIL OPTION                                    |   36 |     36000 |          0 |                      |                      |                  |     383.65 |         795 | No               |               | TESTQA036 | PGUPGRADE108  | 123 STREET |      12345 |   1234567899 | test@test.com | No        |               |              |             |                |                  |                  |       10000 |         15000 | 0.5 |        10000 |        25000 | KIA MOTORS FINANCE           |
      |        9 | RollsRoyce     |            | R5054115 | rrqaauto | ******   |         | SCA665C51GUX86012 |             |              |                       |      | 2018-01-21    | 2020-01-17           | Yes              |                       | New              | FINANCE     |      100 | RR GAP PROTECTION                |                             | GAP PROTECTION                                         |   56 |           |          0 |                      |                      |                  |        550 |         600 | No               |               | TESTQA038 | PGUPGRADE109  | 123 STREET |      30328 |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |       10000 |         15000 | 0.5 |              |              | BMW Financial Service NA LLC |
      |       10 | Penske         | English-US | PAG45855 | pkqaauto | ******   |         | ZFF73SKA6G0215312 |             |              |                       | 2016 | 2017-06-27    | 2020-01-17           | Yes              |                       | NEW              | FINANCE     |     2000 | PENSKE MULTI-COVERAGE PROTECTION | BRONZE BUNDLE WITH COSMETIC |                                                        |   12 |           |          0 |                      |                      |                  |       1765 |         280 | No               |               | TESTQA071 | PGUPGRADE1010 | 123 STREET |      90013 |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |       10000 |         15000 | 0.5 |        10000 |        25000 |                              |
      |       12 | Harley_us      |            | 00HD2075 | hdqausau | ******** |         | 1HD4CR213GC441031 |             |              |                       |      | 02/21/2018    | 01/17/2020           | Yes              |                       | NEW              | FINANCE     |     1000 | HARLEY-DAVIDSON THEFT PROTECTION |                             | THEFT PROTECTION                                       |   60 |           |          0 |                      |                      | 123456789asd     |        190 |         200 | No               |               | TESTQA024 | PGUPGRADE1011 | 123 STREET |      90013 |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |       10000 |         15000 | 0.5 |        10000 |        25000 |                              |

  @SaveContract_CAN__PGUPGRADE_1
  Scenario Outline: Save Contract
    Given Go to url with data as "<TestCase>" and "<Portal>" and "<Language>"and "<Dealer>"
    And Login as "<UserName>" and "<Password>" and "<Captcha>"
    When Click on add New eContract
    And Decode the VIN "<Vin>"
    And Enter contract purchase information "<Vin>" and "<Trim>" and "<Inservicedate>" and "<ContractPurchaseDate>" and "<Vehicle_Purchase>" and "<Vehicle_Purchase_Date>" and "<Vehicle_condtion>" and "<FinanceType>" and "<odometer>" and "<Province>"
    And Select product and get rates "<SelectProduct>" and "<BundleSelection>" and "<Plan>" and "<Term>" and "<TermMiles>" and "<Deductible>" and "<RetailPrice>" and "<DealerCost>" and "<FirstServiceInterval>" and "<FinalServiceInterval>" and "<RegistrationCode>"
    And Verify Dealer Cost and Candian Taxation "<DealerCost>" and "<ExpDealerHST>" and "<ExpDealerGST>" and "<ExpDealerPST>" and "<ExpDealerQST>" and "<ExpDealerCostTotal>"
    And Verify Customer Cost and Candian Taxation "<CustomerCost>" and "<CustomerHST>" and "<CustomerGST>" and "<CustomerPST>" and "<CustomerQST>" and "<ExpTotalCustomerCost>"
    And Enter customer details "<isThisaBussiness>" and "<customerAgreementLanguage>" and "<BussinessName>" and "<FirstName>" and "<LastName>" and "<Address>" and "<PostalCode>" and "<PhoneNumber1>" and "<EmailAddress>" and "<Co-Signer>" and "<cos-First Name>" and "<cos-Last Name>" and "<cos-Address>" and "<cos-Postal Code>" and "<cos-Phone Number 1>" and "<cos-Email Address>" and "<SelectProduct>"
    And Enter vehicle purchase price and finance info "<SelectProduct>" and "<VehicleMSRP>" and "<FinanceAmount>" and  "<APR>" and "<GrossCapCost>" and "<Vehicleprice>"
    And Select Lienholder "<Lienholder>" and "<SelectProduct>"
    And Save the contract
    And Go to the summary page
    Then Logout out from the portal

    Examples: 
      | TestCase | Portal             | Language       | UserName | Dealer   | Password | Vin               | Make            | Model        | Trim      | Year | Inservicedate | Province       | ContractPurchaseDate | Vehicle_Purchase | Vehicle_Purchase_Date | Vehicle_condtion | FinanceType | odometer | SelectProduct                    | BundleSelection | Plan                                                   | Term | TermMiles | Deductible | DealerCost | ExpDealerHST | ExpDealerPST | ExpDealerGST | ExpDealerQST | ExpDealerCostTotal | CustomerCost | CustomerHST | CustomerPST | CustomerGST | CustomerQST | CustTotalCost | FirstServiceInterval | FinalServiceInterval | RegistrationCode | isThisaBussiness | FirstName  | LastName     | customerAgreementLanguage | BussinessName | Address      | PostalCode | PhoneNumber1 | EmailAddress  | Co-Signer | cos-FirstName | cos-LastName | cos-Address | cos-PostalCode | cos-PhoneNumber1 | cos-EmailAddress | VehicleMSRP | FinanceAmount | APR | GrossCapCost | Vehicleprice | Lienholder |
      |        1 | Porsche_Canada     | English-Canada | pcqaauto | PORS2229 | ******   | WP0CA2A80HS220877 | PORSCHE         | 718 BOXSTER  | BASE      | 2017 | 01-17-2020    | Ontario [ ON ] | 01-17-2020           | Yes              | 11/28/2018            | Pre-Owned        | FINANCE     |    18688 | PFS GAP PROTECTION               |                 | Porsche Protection Plan Guaranteed Auto Protection     |   12 | NA        |          0 |        275 |        35.75 |              |              |              |             282.50 |          750 |       97.50 |             |             |             |               |                      |                      |                  | No               | TESTQA001  | PGUPGRADE101 | French-Canada             |               | 123 STREET   | K1A0A1     |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |       20000 |         15000 | 0.5 |        10000 |        25000 |            |
      |        2 | Bentley_Canada     | English-Canada | bcqaauto | BENT4013 | ******   | SJAAC2ZV2HC015116 | BENTLEY         | BENTAYGA W12 | BASE      | 2017 | 01-17-2020    | Ontario [ ON ] | 01-17-2020           | Yes              | 11/28/2018            | New              | LEASE       |       11 | BFS LEASE-END PROTECTION         |                 | Bentley Protection Plan Lease-End Protection           |   36 | NA        |          0 |       1640 |       213.20 |              |              |              |            1886.00 |         2000 |      246.00 |             |             |             |               |                      |                      |                  | No               | TESTQA006  | PGUPGRADE102 | French-Canada             |               | 123 STREET   | K1A0A1     |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |       20000 |         15000 | 0.5 |        10000 |        25000 |            |
      |        3 | Lamborghini_Canada | English-Canada | lcqaauto | LAMB6703 | ******   | ZHWUC1ZD4HLA05825 | LAMBORGHINI     | AVENTADOR    | LP700_4   | 2017 | 01-17-2020    | Ontario [ ON ] | 01-17-2020           | Yes              | 11/28/2018            | Pre-Owned        | FINANCE     |    18688 | LFS GAP PROTECTION               |                 | Lamborghini Protection Plan Guaranteed Auto Protection |   12 | NA        |          0 |        690 |        89.70 |              |              |              |             793.50 |          800 |      103.50 |             |             |             |               |                      |                      |                  | No               | TESTQA009  | PGUPGRADE103 | French-Canada             |               | 123 STREET   | K1A0A1     |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |       20000 |         15000 | 0.5 |        10000 |        25000 |            |
      |        4 | Harley_Canada      | English-Canada | hdqaauto | 0HD50020 | ******   | 1HD4CR213GC441031 | HARLEY-DAVIDSON | SPORTSTER    | SUPERFLOW | 2016 | 2017-08-19    | Alberta [ AB ] | 2020-01-17           | Yes              |                       | New              | CASH        |     1000 | HARLEY-DAVIDSON THEFT PROTECTION |                 | THEFT PROTECTION                                       |   60 |           |          0 |        175 |              |              |         8.75 |              |             183.75 |          200 |             |             |        8.75 |             |        208.75 |                      |                      | TESTTHEFT001     | No               | TESTQA014  | PGUPGRADE104 | English-Canada            |               | 123 STREET   | V1Z 1A3    |   5646556564 | test@test.com | No        |               |              |             |                |                  |                  |       10000 |         15000 | 0.5 |        10000 |        25000 |            |
      |        5 | Motorrad           | English-Canada | moqaauto | MTC09220 | ******   | WB10C2301JZL08559 |                 |              |           |      | 2018-06-10    | Alberta [ AB ] | 2020-01-17           | Yes              |                       | Pre-Owned        | CASH        |      111 | MOTORRAD CANADA VSC              |                 | VSC PLATINUM COVERAGE                                  |   60 |           |          0 |        730 |              |              |        36.50 |              |                    |          730 |             |             |       36.50 |             |               |                      |                      |                  | No               | TESTQA026  | PGUPGRADE105 | French-Canada             |               | TEST ADDRESS | T0M0A1     |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |       30000 |         10000 | 0.5 |              |        20500 |            |
      |        6 | BMW_MINI           | English-Canada | bmqaauto | BMC06117 | ******   | WBA1F9C56GV509209 |                 |              |           |      | 2018-04-01    | Alberta [ AB ] | 2020-01-17           | Yes              |                       | New              | CASH        |      111 | BMW CANADA VSC                   |                 | VSC PLATINUM COVERAGE - IN WARRANTY                    |   72 |     80000 |          0 |       1400 |              |              |        70.00 |              |                    |         1555 |             |             |          20 |             |               |                      |                      |                  | No               | TESTQA018  | PGUPGRADE106 | French-Canada             |               | TEST ADDRESS | T0M0A1     |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |       30000 |         10000 | 0.5 |              |        20500 |            |
      |        7 | Honda              | English-Canada | hoqaauto | HOND1100 | ******   | 2HGFC2F81KH500257 |                 |              |           |      | 2019-05-10    | Alberta [ AB ] | 2020-01-17           | Yes              |                       | New              | LEASE       |      111 | HONDA LEASE-GUARD                |                 | HONDA LEASE-GUARD                                      |   72 |           |            |        548 |              |              |        27.40 |              |                    |          898 |             |             |       44.90 |             |               |                      |                      |                  | No               | TESTHQA001 | PGUPGRADE107 | French-Canada             |               | TEST ADDRESS | T0M0A1     |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |             |               |     |              |              |            |
      |        8 | Acura              | English-Canada | acqaauto | ACUR2002 | ******   | 5J8TC2H32KL010109 |                 |              |           |      | 2019-05-10    | Alberta [ AB ] | 2020-01-17           | Yes              |                       | New              | LEASE       |      121 | ACURA LEASE-GUARD                |                 | ACURA LEASE-GUARD                                      |   60 |           |            |        688 |              |              |        34.40 |              |                    |         1188 |             |             |       59.40 |             |               |                      |                      |                  | No               | TESTHQA002 | PGUPGRADE108 | French-Canada             |               | TEST ADDRESS | T0M0A1     |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |             |               |     |              |              |            |

  @SubmitContract_USA_PGUPGRADE_1
  Scenario Outline: Save and Submit the New Contract
    Given Go to url with data as "<TestCase>" and "<Portal>" and "<Language>"and "<Dealer>"
    And Login as "<UserName>" and "<Password>" and "<Captcha>"
    When Click on add New eContract
    And Decode the VIN "<Vin>"
    And Enter contract purchase information "<Vin>" and "<Trim>" and "<Inservicedate>" and "<ContractPurchaseDate>" and "<Vehicle_Purchase>" and "<Vehicle_Purchase_Date>" and "<Vehicle_condtion>" and "<FinanceType>" and "<odometer>" and "<Province>"
    And Select product and get rates "<SelectProduct>" and "<BundleSelection>" and "<Plan>" and "<Term>" and "<TermMiles>" and "<Deductible>" and "<RetailPrice>" and "<DealerCost>" and "<FirstServiceInterval>" and "<FinalServiceInterval>" and "<RegistrationCode>"
    And Verify Dealer Cost and Retail Price "<DealerCost>" and "<RetailPrice>"
    And Enter customer details "<isThisaBussiness>" and "<customerAgreementLanguage>" and "<BussinessName>" and "<FirstName>" and "<LastName>" and "<Address>" and "<PostalCode>" and "<PhoneNumber1>" and "<EmailAddress>" and "<Co-Signer>" and "<cos-First Name>" and "<cos-Last Name>" and "<cos-Address>" and "<cos-Postal Code>" and "<cos-Phone Number 1>" and "<cos-Email Address>" and "<SelectProduct>"
    And Enter vehicle purchase price and finance info "<SelectProduct>" and "<VehicleMSRP>" and "<FinanceAmount>" and  "<APR>" and "<GrossCapCost>" and "<Vehicleprice>"
    And Select Lienholder "<Lienholder>" and "<SelectProduct>"
    And Save the contract
    And Go to the summary page
    And Click on Manage Saved eContracts
    And Select the contract with Last Name "<LastName>", VIN "<Vin>", Product "<SelectProduct>" and Portal "<Portal>"
    And Submit the contract
    Then Logout out from the portal

    Examples: 
      | TestCase | Portal         | Language   | Dealer   | UserName | Password | Captcha | Vin               | Make        | Model        | Trim                  | Year | Inservicedate | ContractPurchaseDate | Vehicle_Purchase | Vehicle_Purchase_Date | Vehicle_condtion | FinanceType | odometer | SelectProduct                    | BundleSelection             | Plan                                                   | Term | TermMiles | Deductible | FirstServiceInterval | FinalServiceInterval | RegistrationCode | DealerCost | RetailPrice | isThisaBussiness | BussinessName | FirstName | LastName      | Address    | PostalCode | PhoneNumber1 | EmailAddress  | Co-Signer | cos-FirstName | cos-LastName | cos-Address | cos-PostalCode | cos-PhoneNumber1 | cos-EmailAddress | VehicleMSRP | FinanceAmount | APR | GrossCapCost | Vehicleprice | Lienholder                   |
      |        1 | Volkswagen_VCI |            | VW422530 | vwqaauto | ******** |         | 1V2AP2CA4JC562612 | VOLKSWAGEN  | ATLAS        | 2.0T S                | 2018 | 01-17-2020    | 01-17-2020           | Yes              | 01-17-2020            | New              | LEASE       |       14 | VW LEASE PROTECTION              |                             | LEASE PROTECTION                                       |   48 |         0 |          0 |                      |                      |                  |        575 |         967 | No               |               | TESTQA003 | PGUPGRADE121  | 123 STREET |      30328 |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |       20000 |         15000 | 0.5 |        10000 |        25000 |                              |
      |        2 | Audi_VCI       |            | AU422A03 | auqaauto | ******** |         | WA1VCAFP5HA038612 | AUDI        | SQ5          | 3.0T QUATTRO PRESTIGE | 2017 | 01-17-2020    | 01-17-2020           | Yes              | 01-17-2020            | New              | LEASE       |      151 | AUDI LEASE PROTECTION            |                             | LEASE END PROTECTION                                   |   36 |         0 |          0 |                      |                      |                  |        590 |         574 | No               |               | TESTQA014 | PGUPGRADE122  | 123 STREET |      30328 |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |       20000 |         15000 | 0.5 |        10000 |        25000 |                              |
      |        3 | Ducati_vci     |            | DU101156 | duqaauto | ******** |         | ZDM14BPW3EB026112 | DUCATI      | PANIGALE     | 1199 S                | 2014 | 01-17-2020    | 01-17-2020           | Yes              | 01-17-2020            | New              | FINANCE     |      100 | DUCATI TIRE & WHEEL PROTECTION   |                             | TIRE & WHEEL PROTECTION                                |   24 |         0 |          0 |                      |                      |                  |        285 |         299 | No               |               | TESTQA023 | PGUPGRADE123  | 123 STREET |      30328 |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |       20000 |         15000 | 0.5 |        10000 |        25000 |                              |
      |        4 | Porsche_US     |            | PORS1820 | prqaauto | ******   |         | WP0CA2A80HS220877 | PORSCHE     | 718 BOXSTER  | BASE                  | 2017 | 05-10-2018    | 01-17-2020           | Yes              | 09/26/2018            | Pre-Owned        | FINANCE     |    18688 | QUALITYSHIELD GAP PROTECTION     |                             | GAP PROTECTION                                         |   12 | NA        |          0 |                      |                      |                  |        190 |         210 | No               |               | TESTQA031 | PGUPGRADE124  | 123 STREET |      30328 |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |       20000 |         15000 | 0.5 |        10000 |        25000 |                              |
      |        5 | Bentley_US     |            | BENT3071 | bnqaauto | ******   |         | SJAAC2ZV2HC015116 | BENTLEY     | BENTAYGA W12 | BASE                  | 2017 | 05-10-2018    | 01-17-2020           | Yes              | 09/26/2018            | New              | LEASE       |       11 | BFS LEASE-END PROTECTION         |                             | Bentley Protection Plan Lease-End Protection           |   36 | NA        |          0 |                      |                      |                  |       1840 |        1860 | No               |               | TESTQA041 | PGUPGRADE125  | 123 STREET |      30328 |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |       20000 |         15000 | 0.5 |        10000 |        25000 |                              |
      |        6 | Lamborghini_US |            | LAMB5109 | lmqaauto | ******   |         | ZHWUC1ZD4HLA05825 | LAMBORGHINI | AVENTADOR    | LP700_4               | 2017 | 05-10-2018    | 01-17-2020           | Yes              | 09/26/2018            | Pre-Owned        | FINANCE     |    18688 | LFS GAP PROTECTION               |                             | Lamborghini Protection Plan Guaranteed Auto Protection |   12 | NA        |          0 |                      |                      |                  |        560 |         580 | No               |               | TESTQA046 | PGUPGRADE126  | 123 STREET |      30328 |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |       20000 |         15000 | 0.5 |        10000 |        25000 |                              |
      |        7 | Vroom          |            | 00AA1005 | vrqaauto | ******** |         | 3VW447AU2HM033520 |             |              |                       | 2016 | 2017-06-27    | 2020-01-17           | Yes              |                       | Pre-Owned        | FINANCE     |     2000 | VROOM VSC PROTECTION             |                             | PLATINUM COVERAGE                                      |   48 |    100000 |        100 |                      |                      |                  |       1028 |        1374 | No               |               | TESTQA025 | PGUPGRADE127  | 123 STREET |      90013 |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |       10000 |         15000 | 0.5 |        10000 |        25000 |                              |
      |        8 | Fuccillo       |            | HYUNY062 | fcqaauto | ******   |         | KMHD84LF5HU066464 |             |              |                       |      | 2017-03-09    | 2020-01-17           | Yes              |                       | New              | FINANCE     |       53 | FUCCILLO PREPAID MAINTENANCE     |                             | STANDARD OIL OPTION                                    |   36 |     36000 |          0 |                      |                      |                  |     383.65 |         795 | No               |               | TESTQA036 | PGUPGRADE128  | 123 STREET |      12345 |   1234567899 | test@test.com | No        |               |              |             |                |                  |                  |       10000 |         15000 | 0.5 |        10000 |        25000 | KIA MOTORS FINANCE           |
      |        9 | RollsRoyce     |            | R5054115 | rrqaauto | ******   |         | SCA665C51GUX86012 |             |              |                       |      | 2018-01-21    | 2020-01-17           | Yes              |                       | New              | FINANCE     |      100 | RR GAP PROTECTION                |                             | GAP PROTECTION                                         |   56 |           |          0 |                      |                      |                  |        550 |         600 | No               |               | TESTQA038 | PGUPGRADE129  | 123 STREET |      30328 |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |       10000 |         15000 | 0.5 |              |              | BMW Financial Service NA LLC |
      |       10 | Penske         | English-US | PAG45855 | pkqaauto | ******   |         | ZFF73SKA6G0215312 |             |              |                       | 2016 | 2017-06-27    | 2020-01-17           | Yes              |                       | NEW              | FINANCE     |     2000 | PENSKE MULTI-COVERAGE PROTECTION | BRONZE BUNDLE WITH COSMETIC |                                                        |   12 |           |          0 |                      |                      |                  |       1765 |         280 | No               |               | TESTQA071 | PGUPGRADE1210 | 123 STREET |      90013 |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |       10000 |         15000 | 0.5 |        10000 |        25000 |                              |
      |       12 | Harley_us      |            | 00HD2075 | hdqausau | ******** |         | 1HD4CR213GC441031 |             |              |                       |      | 02/21/2018    | 01/17/2020           | Yes              |                       | NEW              | FINANCE     |     1000 | HARLEY-DAVIDSON THEFT PROTECTION |                             | THEFT PROTECTION                                       |   60 |           |          0 |                      |                      | 123456789asd     |        190 |         200 | No               |               | TESTQA024 | PGUPGRADE1211 | 123 STREET |      90013 |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |       10000 |         15000 | 0.5 |        10000 |        25000 |                              |

  @SubmitContract_CAN_PGUPGRADE_1
  Scenario Outline: Save and Submit the New Contract
    Given Go to url with data as "<TestCase>" and "<Portal>" and "<Language>"and "<Dealer>"
    And Login as "<UserName>" and "<Password>" and "<Captcha>"
    When Click on add New eContract
    And Decode the VIN "<Vin>"
    And Enter contract purchase information "<Vin>" and "<Trim>" and "<Inservicedate>" and "<ContractPurchaseDate>" and "<Vehicle_Purchase>" and "<Vehicle_Purchase_Date>" and "<Vehicle_condtion>" and "<FinanceType>" and "<odometer>" and "<Province>"
    And Select product and get rates "<SelectProduct>" and "<BundleSelection>" and "<Plan>" and "<Term>" and "<TermMiles>" and "<Deductible>" and "<RetailPrice>" and "<DealerCost>" and "<FirstServiceInterval>" and "<FinalServiceInterval>" and "<RegistrationCode>"
    And Verify Dealer Cost and Candian Taxation "<DealerCost>" and "<ExpDealerHST>" and "<ExpDealerGST>" and "<ExpDealerPST>" and "<ExpDealerQST>" and "<ExpDealerCostTotal>"
    And Verify Customer Cost and Candian Taxation "<CustomerCost>" and "<CustomerHST>" and "<CustomerGST>" and "<CustomerPST>" and "<CustomerQST>" and "<ExpTotalCustomerCost>"
    And Enter customer details "<isThisaBussiness>" and "<customerAgreementLanguage>" and "<BussinessName>" and "<FirstName>" and "<LastName>" and "<Address>" and "<PostalCode>" and "<PhoneNumber1>" and "<EmailAddress>" and "<Co-Signer>" and "<cos-First Name>" and "<cos-Last Name>" and "<cos-Address>" and "<cos-Postal Code>" and "<cos-Phone Number 1>" and "<cos-Email Address>" and "<SelectProduct>"
    And Enter vehicle purchase price and finance info "<SelectProduct>" and "<VehicleMSRP>" and "<FinanceAmount>" and  "<APR>" and "<GrossCapCost>" and "<Vehicleprice>"
    And Select Lienholder "<Lienholder>" and "<SelectProduct>"
    And Save the contract
    And Go to the summary page
    And Click on Manage Saved eContracts
    And Select the contract with Last Name "<LastName>", VIN "<Vin>", Product "<SelectProduct>" and Portal "<Portal>"
    And Submit the contract
    Then Logout out from the portal

    Examples: 
      | TestCase | Portal             | Language       | UserName | Dealer   | Password | Vin               | Make            | Model        | Trim      | Year | Inservicedate | Province       | ContractPurchaseDate | Vehicle_Purchase | Vehicle_Purchase_Date | Vehicle_condtion | FinanceType | odometer | SelectProduct                    | BundleSelection | Plan                                                   | Term | TermMiles | Deductible | DealerCost | ExpDealerHST | ExpDealerPST | ExpDealerGST | ExpDealerQST | ExpDealerCostTotal | CustomerCost | CustomerHST | CustomerPST | CustomerGST | CustomerQST | CustTotalCost | FirstServiceInterval | FinalServiceInterval | RegistrationCode | isThisaBussiness | FirstName  | LastName     | customerAgreementLanguage | BussinessName | Address      | PostalCode | PhoneNumber1 | EmailAddress  | Co-Signer | cos-FirstName | cos-LastName | cos-Address | cos-PostalCode | cos-PhoneNumber1 | cos-EmailAddress | VehicleMSRP | FinanceAmount | APR | GrossCapCost | Vehicleprice | Lienholder |
      |        1 | Porsche_Canada     | English-Canada | pcqaauto | PORS2229 | ******   | WP0CA2A80HS220877 | PORSCHE         | 718 BOXSTER  | BASE      | 2017 | 01-17-2020    | Ontario [ ON ] | 01-17-2020           | Yes              | 11/28/2018            | Pre-Owned        | FINANCE     |    18688 | PFS GAP PROTECTION               |                 | Porsche Protection Plan Guaranteed Auto Protection     |   12 | NA        |          0 |        275 |        35.75 |              |              |              |             282.50 |          750 |       97.50 |             |             |             |               |                      |                      |                  | No               | TESTQA001  | PGUPGRADE121 | French-Canada             |               | 123 STREET   | K1A0A1     |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |       20000 |         15000 | 0.5 |        10000 |        25000 |            |
      |        2 | Bentley_Canada     | English-Canada | bcqaauto | BENT4013 | ******   | SJAAC2ZV2HC015116 | BENTLEY         | BENTAYGA W12 | BASE      | 2017 | 01-17-2020    | Ontario [ ON ] | 01-17-2020           | Yes              | 11/28/2018            | New              | LEASE       |       11 | BFS LEASE-END PROTECTION         |                 | Bentley Protection Plan Lease-End Protection           |   36 | NA        |          0 |       1640 |       213.20 |              |              |              |            1886.00 |         2000 |      246.00 |             |             |             |               |                      |                      |                  | No               | TESTQA006  | PGUPGRADE122 | French-Canada             |               | 123 STREET   | K1A0A1     |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |       20000 |         15000 | 0.5 |        10000 |        25000 |            |
      |        3 | Lamborghini_Canada | English-Canada | lcqaauto | LAMB6703 | ******   | ZHWUC1ZD4HLA05825 | LAMBORGHINI     | AVENTADOR    | LP700_4   | 2017 | 01-17-2020    | Ontario [ ON ] | 01-17-2020           | Yes              | 11/28/2018            | Pre-Owned        | FINANCE     |    18688 | LFS GAP PROTECTION               |                 | Lamborghini Protection Plan Guaranteed Auto Protection |   12 | NA        |          0 |        690 |        89.70 |              |              |              |             793.50 |          800 |      103.50 |             |             |             |               |                      |                      |                  | No               | TESTQA009  | PGUPGRADE123 | French-Canada             |               | 123 STREET   | K1A0A1     |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |       20000 |         15000 | 0.5 |        10000 |        25000 |            |
      |        4 | Harley_Canada      | English-Canada | hdqaauto | 0HD50020 | ******   | 1HD4CR213GC441031 | HARLEY-DAVIDSON | SPORTSTER    | SUPERFLOW | 2016 | 2017-08-19    | Alberta [ AB ] | 2020-01-17           | Yes              |                       | New              | CASH        |     1000 | HARLEY-DAVIDSON THEFT PROTECTION |                 | THEFT PROTECTION                                       |   60 |           |          0 |        175 |              |              |         8.75 |              |             183.75 |          200 |             |             |        8.75 |             |        208.75 |                      |                      | TESTTHEFT001     | No               | TESTQA014  | PGUPGRADE124 | English-Canada            |               | 123 STREET   | V1Z 1A3    |   5646556564 | test@test.com | No        |               |              |             |                |                  |                  |       10000 |         15000 | 0.5 |        10000 |        25000 |            |
      |        5 | Motorrad           | English-Canada | moqaauto | MTC09220 | ******   | WB10C2301JZL08559 |                 |              |           |      | 2018-06-10    | Alberta [ AB ] | 2020-01-17           | Yes              |                       | Pre-Owned        | CASH        |      111 | MOTORRAD CANADA VSC              |                 | VSC PLATINUM COVERAGE                                  |   60 |           |          0 |        730 |              |              |        36.50 |              |                    |          730 |             |             |       36.50 |             |               |                      |                      |                  | No               | TESTQA026  | PGUPGRADE125 | French-Canada             |               | TEST ADDRESS | T0M0A1     |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |       30000 |         10000 | 0.5 |              |        20500 |            |
      |        6 | BMW_MINI           | English-Canada | bmqaauto | BMC06117 | ******   | WBA1F9C56GV509209 |                 |              |           |      | 2018-04-01    | Alberta [ AB ] | 2020-01-17           | Yes              |                       | New              | CASH        |      111 | BMW CANADA VSC                   |                 | VSC PLATINUM COVERAGE - IN WARRANTY                    |   72 |     80000 |          0 |       1400 |              |              |        70.00 |              |                    |         1555 |             |             |          20 |             |               |                      |                      |                  | No               | TESTQA018  | PGUPGRADE126 | French-Canada             |               | TEST ADDRESS | T0M0A1     |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |       30000 |         10000 | 0.5 |              |        20500 |            |
      |        7 | Honda              | English-Canada | hoqaauto | HOND1100 | ******   | 2HGFC2F81KH500257 |                 |              |           |      | 2019-05-10    | Alberta [ AB ] | 2020-01-17           | Yes              |                       | New              | LEASE       |      111 | HONDA LEASE-GUARD                |                 | HONDA LEASE-GUARD                                      |   72 |           |            |        548 |              |              |        27.40 |              |                    |          898 |             |             |       44.90 |             |               |                      |                      |                  | No               | TESTHQA001 | PGUPGRADE127 | French-Canada             |               | TEST ADDRESS | T0M0A1     |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |             |               |     |              |              |            |
      |        8 | Acura              | English-Canada | acqaauto | ACUR2002 | ******   | 5J8TC2H32KL010109 |                 |              |           |      | 2019-05-10    | Alberta [ AB ] | 2020-01-17           | Yes              |                       | New              | LEASE       |      121 | ACURA LEASE-GUARD                |                 | ACURA LEASE-GUARD                                      |   60 |           |            |        688 |              |              |        34.40 |              |                    |         1188 |             |             |       59.40 |             |               |                      |                      |                  | No               | TESTHQA002 | PGUPGRADE128 | French-Canada             |               | TEST ADDRESS | T0M0A1     |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |             |               |     |              |              |            |
