Feature: To Test EAS Portal Functionalities

  @SaveContract__US_portal_QUICK_Regression
  Scenario Outline: Add a New Contract
    Given Go to url with data as "<TestCase>" and "<Portal>" and "<Language>"and "<Dealer>"
    And Login as "<UserName>" and "<Password>" and "<Captcha>"
    When Click on add New eContract
    And Decode the VIN "<Vin>"
    And Enter contract purchase information "<Vin>" and "<Trim>" and "<Inservicedate>" and "<ContractPurchaseDate>" and "<Vehicle_Purchase>" and "<Vehicle_Purchase_Date>" and "<Vehicle_condtion>" and "<FinanceType>" and "<odometer>" and "<Province>"
    And Select product and get rates "<SelectProduct>" and "<BundleSelection>" and "<Plan>" and "<Term>" and "<TermMiles>" and "<Deductible>" and "<RetailPrice>" and "<DealerCost>" and "<FirstServiceInterval>" and "<FinalServiceInterval>" and "<RegistrationCode>"
    And Verify Dealer Cost and Retail Price "<DealerCost>" and "<RetailPrice>"
    And Enter customer details "<isThisaBussiness>" and "<customerAgreementLanguage>" and "<BussinessName>" and "<FirstName>" and "<LastName>" and "<Address>" and "<PostalCode>" and "<PhoneNumber1>" and "<EmailAddress>" and "<Co-Signer>" and "<cos-First Name>" and "<cos-Last Name>" and "<cos-Address>" and "<cos-Postal Code>" and "<cos-Phone Number 1>" and "<cos-Email Address>" and "<SelectProduct>"
    And Enter vehicle purchase price and finance info "<SelectProduct>" and "<VehicleMSRP>" and "<FinanceAmount>" and  "<APR>" and "<GrossCapCost>" and "<Vehicleprice>"
    And Select Lienholder "<Lienholder>" and "<SelectProduct>"
    And Save the contract
    And Go to the summary page
    Then Logout out from the portal

    Examples: 
      | TestCase | Portal             | Language   | Dealer   | UserName | Password | Captcha | Vin               | Make        | Model        | Trim                   | Year | Inservicedate | ContractPurchaseDate | Vehicle_Purchase | Vehicle_Purchase_Date | Vehicle_condtion | FinanceType | odometer | SelectProduct                    | BundleSelection             | Plan                                         | Term | TermMiles | Deductible | FirstServiceInterval | FinalServiceInterval | RegistrationCode | DealerCost | RetailPrice | isThisaBussiness | BussinessName | FirstName | LastName  | Address    | PostalCode | PhoneNumber1 | EmailAddress  | Co-Signer | cos-FirstName | cos-LastName | cos-Address | cos-PostalCode | cos-PhoneNumber1 | cos-EmailAddress | VehicleMSRP | FinanceAmount | APR | GrossCapCost | Vehicleprice | Lienholder                   |  |
      |        1 | Volkswagen_VCI     |            | VW426061 | vwqaauto | ******   |         | WA1LAAGE0KB003372 | Audi        | E-Tron       | Premium Plus           | 2019 | 03-28-2022    | 03-28-2022           | Yes              | 01-25-2021            | Pre-Owned        | FINANCE     |    18688 | QP VEHICLE SERVICE PROTECTION    |                             | PLATINUM COVERAGE                            |   48 |     36000 |        100 |                      |                      |                  |       1230 |        2888 | No               |               | TESTQA001 | TESTQA001 | 123 STREET |      30328 |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |       20000 |         15000 | 0.5 |        10000 |        25000 |                              |  |
      |        2 | Audi_VCI           |            | AU422A03 | auqaauto | ******   |         | TRUC5AFV3H1003352 | AUDI        | TT           | 2.0T QUATTRO           | 2017 | 03-28-2022    | 03-28-2022           | Yes              | 01-25-2021            | New              | FINANCE     |       35 | AUDI VEHICLE SERVICE PROTECTION  |                             | PLATINUM COVERAGE - IN WARRANTY              |   96 |    100000 |        100 |                      |                      |                  |       3545 |        3390 | No               |               | TESTQA002 | TESTQA002 | 123 STREET |      30328 |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |       20000 |         15000 | 0.5 |        10000 |        25000 |                              |  |
      |        3 | Ducati_vci         |            | DU101156 | duqaauto | ******   |         | ZDM14BPW3EB023352 | DUCATI      | PANIGALE     |                   1199 | 2014 | 03-28-2022    | 03-28-2022           | Yes              | 01-25-2021            | Pre-Owned        | REVOLVING   |    25000 | DUCATI THEFT PROTECTION          |                             | DUTP5000                                     |   72 |         0 |          0 |                      |                      |                  |        130 |         175 | No               |               | TESTQA003 | TESTQA003 | 123 STREET |      30328 |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |       20000 |         15000 | 0.5 |        10000 |        25000 |                              |  |
      |        4 | QualityProtect_VCI |            | QPA00007 | qpqaauto | ******   |         | 3VW217AU0HM063332 | VOLKSWAGEN  | GOLF         | 1.8T WOLFSBURG EDITION | 2017 | 03-28-2022    | 03-28-2022           | Yes              | 01-25-2021            | New              | FINANCE     |      120 | QP VEHICLE SERVICE PROTECTION    |                             | GOLD COVERAGE                                |   72 |     85000 |          0 |                      |                      |                  |        860 |        1188 | No               |               | TESTQA004 | TESTQA004 | 123 STREET |      30328 |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |       20000 |         15000 | 0.5 |        10000 |        25000 |                              |  |
      |        5 | Porsche_US         |            | PORS1820 | prqaauto | ******   |         | WP0AD2A93HS163332 | PORSCHE     |          911 | TURBO S                | 2017 | 03-28-2022    | 03-28-2022           | Yes              | 08/10/2020            | New              | LEASE       |       11 | PFS LEASE-END PROTECTION         |                             | Porsche Protection Plan Lease-End Protection |   36 | NA        |          0 |                      |                      |                  |        924 |         950 | No               |               | TESTQA005 | TESTQA005 | 123 STREET |      30328 |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |       20000 |         15000 | 0.5 |        10000 |        25000 |                              |  |
      |        6 | Bentley_US         |            | BENT3071 | bnqaauto | ******   |         | SJAAC2ZV2HC013352 | BENTLEY     | BENTAYGA W12 | BASE                   | 2017 | 03-28-2022    | 03-28-2022           | Yes              | 09/26/2018            | New              | LEASE       |       11 | BFS LEASE-END PROTECTION         |                             | Bentley Protection Plan Lease-End Protection |   36 | NA        |          0 |                      |                      |                  |       1956 |        3696 | No               |               | TESTQA041 | TESTQA041 | 123 STREET |      30328 |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |       20000 |         15000 | 0.5 |        10000 |        25000 |                              |  |
      |        7 | Lamborghini_US     |            | LAMB5109 | lmqaauto | ******   |         | ZHWUC1ZD4HLA03352 | LAMBORGHINI | AVENTADOR    | LP700_4                | 2017 | 03-28-2022    | 03-28-2022           | Yes              | 09/26/2018            | Pre-Owned        | FINANCE     |    18688 | LFS GAP PLUS                     |                             | Lamborghini GAP PLUS                         |   12 | NA        |          0 |                      |                      |                  |        585 |         585 | No               |               | TESTQA046 | TESTQA046 | 123 STREET |      30328 |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |       20000 |         15000 | 0.5 |        10000 |        25000 |                              |  |
      |        8 | Vroom              |            | 00AA1005 | vrqaauto | ******** |         | 5YJSA1H18EFP53352 |             |              |                        | 2014 | 2022-03-28    | 2022-03-28           | Yes              |                       | Pre-Owned        | FINANCE     |     2000 | VROOM EVEHICLE VSC PROTECTION    |                             | PLATINUM COVERAGE                            |   72 |     85000 |        100 |                      |                      |                  |       1720 |        2740 | No               |               | TESTQA008 | TESTQA008 | 123 STREET |      90013 |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |       10000 |         15000 | 0.5 |        10000 |        25000 |                              |  |
      |        9 | RollsRoyce         |            | R5054115 | rrqaauto | ******   |         | SCA665C51GUX83353 |             |              |                        |      | 2022-03-28    | 2022-03-28           | Yes              |                       | New              | FINANCE     |      100 | RR GAP PROTECTION                |                             | GAP PROTECTION                               |   56 |           |          0 |                      |                      |                  |        550 |         600 | No               |               | TESTQA009 | TESTQA009 | 123 STREET |      30328 |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |       10000 |         15000 | 0.5 |              |              | BMW Financial Service NA LLC |  |
      |       10 | Penske             | English-US | PAG45855 | pkqaauto | ******   |         | ZFF73SKA6G0253353 |             |              |                        | 2016 | 2022-03-28    | 2022-03-28           | Yes              |                       | NEW              | FINANCE     |     2000 | PENSKE MULTI-COVERAGE PROTECTION | BRONZE BUNDLE WITH COSMETIC |                                              |   12 |           |          0 |                      |                      |                  |       1765 |         280 | No               |               | TESTQA010 | TESTQA010 | 123 STREET |      90013 |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |       10000 |         15000 | 0.5 |        10000 |        25000 |                              |  |
      |       11 | Harley_us          |            | 00HD0262 | hdqausau | ******** |         | 1HD4CR213GC443353 |             |              |                        |      | 2022-03-28    | 03/28/2022           | Yes              |                       | NEW              | CASH        |     5000 | HARLEY-DAVIDSON THEFT PROTECTION |                             | THEFT PROTECTION                             |   60 |           |          0 |                      |                      | TESTTHEFT003     |        190 |         480 | No               |               | TESTQA011 | TESTQA011 | 123 STREET |      12345 |   5646556564 | test@test.com | No        |               |              |             |                |                  |                  |       10000 |         15000 | 0.5 |        10000 |        25000 |                              |  |
      |       12 | Fuccillo           |            | HYUNY062 | fcqaauto | ******   |         | KMHD84LF5HU063353 |             |              |                        |      | 2022-03-28    | 2022-03-28           | Yes              |                       | New              | FINANCE     |       53 | FUCCILLO PREPAID MAINTENANCE     |                             | STANDARD OIL OPTION                          |   36 |     36000 |          0 |                      |                      |                  |     383.65 |         795 | No               |               | TESTQA036 | TESTQA036 | 123 STREET |      12345 |   1234567899 | test@test.com | No        |               |              |             |                |                  |                  |       10000 |         15000 | 0.5 |        10000 |        25000 | KIA MOTORS FINANCE           |  |

  @SaveContract_Canadian_portal_QUICK_Regression
  Scenario Outline: Save Contract
    Given Go to url with data as "<TestCase>" and "<Portal>" and "<Language>"and "<Dealer>"
    And Login as "<UserName>" and "<Password>" and "<Captcha>"
    When Click on add New eContract
    And Decode the VIN "<Vin>"
    And Enter contract purchase information "<Vin>" and "<Trim>" and "<Inservicedate>" and "<ContractPurchaseDate>" and "<Vehicle_Purchase>" and "<Vehicle_Purchase_Date>" and "<Vehicle_condtion>" and "<FinanceType>" and "<odometer>" and "<Province>"
    And Select product and get rates "<SelectProduct>" and "<BundleSelection>" and "<Plan>" and "<Term>" and "<TermMiles>" and "<Deductible>" and "<RetailPrice>" and "<DealerCost>" and "<FirstServiceInterval>" and "<FinalServiceInterval>" and "<RegistrationCode>"
    And Verify Dealer Cost and Candian Taxation "<DealerCost>" and "<ExpDealerHST>" and "<ExpDealerGST>" and "<ExpDealerPST>" and "<ExpDealerQST>" and "<ExpDealerCostTotal>"
    And Verify Customer Cost and Candian Taxation "<CustomerCost>" and "<CustomerHST>" and "<CustomerGST>" and "<CustomerPST>" and "<CustomerQST>" and "<ExpTotalCustomerCost>"
    And Enter customer details "<isThisaBussiness>" and "<customerAgreementLanguage>" and "<BussinessName>" and "<FirstName>" and "<LastName>" and "<Address>" and "<PostalCode>" and "<PhoneNumber1>" and "<EmailAddress>" and "<Co-Signer>" and "<cos-First Name>" and "<cos-Last Name>" and "<cos-Address>" and "<cos-Postal Code>" and "<cos-Phone Number 1>" and "<cos-Email Address>" and "<SelectProduct>"
    And Enter vehicle purchase price and finance info "<SelectProduct>" and "<VehicleMSRP>" and "<FinanceAmount>" and  "<APR>" and "<GrossCapCost>" and "<Vehicleprice>"
    And Select Lienholder "<Lienholder>" and "<SelectProduct>"
    And Save the contract
    And Go to the summary page
    Then Logout out from the portal

    Examples: 
      | TestCase | Portal             | Language       | UserName | Dealer   | Password | Vin               | Make            | Model        | Trim    | Year | Inservicedate | Province       | ContractPurchaseDate | Vehicle_Purchase | Vehicle_Purchase_Date | Vehicle_condtion | FinanceType | odometer | SelectProduct                       | BundleSelection | Plan                                               | Term | TermMiles | Deductible | DealerCost | ExpDealerHST | ExpDealerPST | ExpDealerGST | ExpDealerQST | ExpDealerCostTotal | CustomerCost | CustomerHST | CustomerPST | CustomerGST | CustomerQST | CustTotalCost | FirstServiceInterval | FinalServiceInterval | RegistrationCode | isThisaBussiness | FirstName | LastName  | customerAgreementLanguage | BussinessName | Address      | PostalCode | PhoneNumber1 | EmailAddress  | Co-Signer | cos-FirstName | cos-LastName | cos-Address | cos-PostalCode | cos-PhoneNumber1 | cos-EmailAddress | VehicleMSRP | FinanceAmount | APR | GrossCapCost | Vehicleprice | Lienholder |
      |        1 | Porsche_Canada     | English-Canada | pcqaauto | PORS2229 | ******   | WP0CA2A80HS221346 | PORSCHE         | 718 BOXSTER  | BASE    | 2017 | 03-28-2022    | Ontario [ ON ] | 03-28-2022           | Yes              | 08/10/2020            | Pre-Owned        | FINANCE     |    18688 | PFS GAP PROTECTION                  |                 | Porsche Protection Plan Guaranteed Auto Protection |   12 | NA        |          0 |        275 |        35.75 |              |              |              |             310.75 |          750 |       97.50 |             |             |             |               |                      |                      |                  | No               | TESTQA001 | TESTQA001 | French-Canada             |               | 123 STREET   | K1A 0A1    |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |       20000 |         15000 | 0.5 |        10000 |        25000 |            |
      |        2 | Bentley_Canada     | English-Canada | bcqaauto | BENT4013 | ******   | SJAAC4ZV1JC018354 | BENTLEY         | BENTAYGA W12 | BASE    | 2017 | 03-28-2022    | Ontario [ ON ] | 03-28-2022           | Yes              | 08/10/2020            | New              | CASH        |    14999 | BFS MULTI-COVERAGE                  | Platinum        |                                                    |   72 | NA        |        100 |       4895 |       636.35 |              |              |              |            4949.40 |         8760 |     1138.80 |             |             |             |       9627.60 |                      |                      |                  | No               | TESTQA002 | TESTQA002 | French-Canada             |               | 123 STREET   | K1A 0A1    |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |       20000 |         15000 | 0.5 |        10000 |        25000 |            |
      |        3 | Lamborghini_Canada | English-Canada | lcqaauto | LAMB6703 | ******   | ZHWUC1ZD4HLA05363 | LAMBORGHINI     | AVENTADOR    | LP700_4 | 2017 | 03-28-2022    | Ontario [ ON ] | 03-28-2022           | Yes              | 08/10/2020            | Pre-Owned        | FINANCE     |    18688 | LFS GAP PROTECTION                  |                 | Guaranteed Auto Protection                         |   12 | NA        |          0 |        690 |        89.70 |              |              |              |             793.50 |          800 |      103.50 |             |             |             |               |                      |                      |                  | No               | TESTQA003 | TESTQA003 | French-Canada             |               | 123 STREET   | K1A 0A1    |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |       20000 |         15000 | 0.5 |        10000 |        25000 |            |
      |        4 | Harley_Canada      | English-Canada | hdqaauto | 0HD50020 | ******   | 5HD2XAEB4LB800372 | HARLEY-DAVIDSON | LIVEWIRE     | BASE    | 2020 | 2022-03-28    | Alberta [ AB ] | 2022-03-28           | Yes              |                       | Pre-Owned        | CASH        |       11 | HARLEY-DAVIDSON PLANNED MAINTENANCE |                 |                                                    |      |           |          0 |       1436 |              |              |        71.80 |              |            1507.80 |         1500 |             |             |          55 |             |        1555.0 | 48000 KILOMETERS     | 80000 KILOMETERS     |                  | No               | TESTQA004 | TESTQA004 | English-Canada            |               | 123 STREET   | V1Z 1A3    |   5646556564 | test@test.com | No        |               |              |             |                |                  |                  |             |               |     |              |              |            |
      |        5 | Motorrad           | English-Canada | moqaauto | MTC09220 | ******   | WB10C1504JZ316381 |                 |              |         |      | 2022-03-28    | Alberta [ AB ] | 2022-03-28           | Yes              |                       | Pre-Owned        | CASH        |      111 | MOTORRAD CANADA VSC                 |                 | VSC PLATINUM COVERAGE                              |   60 |           |          0 |        720 |              |              |        36.00 |              |                    |         1720 |             |             |       86.00 |             |               |                      |                      |                  | No               | TESTQA005 | TESTQA005 | French-Canada             |               | TEST ADDRESS | T0M0A1     |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |       30000 |         10000 | 0.5 |              |        20500 |            |
      |        6 | BMW_MINI           | English-Canada | bmqaauto | BMC06117 | ******   | WBA1F9C56GV509392 |                 |              |         |      | 2022-03-28    | Alberta [ AB ] | 2022-03-28           | Yes              |                       | New              | CASH        |      111 | BMW CANADA VSC                      |                 | VSC PLATINUM COVERAGE - IN WARRANTY                |   72 |     80000 |          0 |       1650 |              |              |        82.50 |              |                    |         3000 |             |             |      150.00 |             |               |                      |                      |                  | No               | TESTQA006 | TESTQA006 | French-Canada             |               | TEST ADDRESS | T0M0A1     |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |       30000 |         10000 | 0.5 |              |        20500 |            |
      |        7 | BMW_MINI           | English-Canada | miqaauto | MNC09130 | ******   | WMWXP5C5XG2D22313 |                 |              |         |      | 2022-03-28    | Alberta [ AB ] | 2022-03-28           | Yes              |                       | New              | CASH        |    20001 | MINI CANADA VSC                     |                 | VSC PLATINUM COVERAGE - IN WARRANTY                |   72 |     80000 |          0 |       1520 |              |              |        76.00 |              |                    |         2370 |             |             |      118.50 |             |               |                      |                      |                  | No               | TESTQA007 | TESTQA007 | French-Canada             |               | TEST ADDRESS | T0M0A1     |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |       30000 |         10000 | 0.5 |              |        20500 |            |
      |        8 | Honda              | English-Canada | hoqaauto | HOND1100 | ******   | 2HGFC2F81KH500324 |                 |              |         |      | 2022-03-28    | Alberta [ AB ] | 2022-03-28           | Yes              |                       | New              | LEASE       |      111 | HONDA LEASE-GUARD                   |                 | HONDA LEASE-GUARD                                  |   72 |           |            |        548 |              |              |        27.40 |              |                    |          898 |             |             |       44.90 |             |               |                      |                      |                  | No               | TESTQA008 | TESTQA008 | French-Canada             |               | TEST ADDRESS | T0M0A1     |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |             |               |     |              |              |            |
      |        9 | Acura              | English-Canada | acqaauto | ACUR2002 | ******   | 5J8TC2H32KL014335 |                 |              |         |      | 2022-03-28    | Alberta [ AB ] | 2022-03-28           | Yes              |                       | Demo             | LEASE       |      121 | ACURA LEASE-GUARD                   |                 | ACURA LEASE-GUARD                                  |   60 |           |            |        688 |              |              |        34.40 |              |                    |         1188 |             |             |       59.40 |             |               |                      |                      |                  | No               | TESTQA009 | TESTQA009 | English-Canada            |               | TEST ADDRESS | T0M0A1     |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |             |               |     |              |              |            |
