Feature: To Test BMW Portal Functionalities

  @SaveContract_BMW-MINI_QA
  Scenario Outline: Save Contract
    Given Go to url with data as "<TestCase>" and "<Portal>" and "<Language>"and "<Dealer>"
    And Login as "<UserName>" and "<Password>" and "<Captcha>"
    When Click on add New eContract
    And Decode the VIN "<Vin>"
    And Enter contract purchase information "<Vin>" and "<Trim>" and "<Inservicedate>" and "<ContractPurchaseDate>" and "<Vehicle_Purchase>" and "<Vehicle_Purchase_Date>" and "<Vehicle_condtion>" and "<FinanceType>" and "<odometer>" and "<Province>"
    And Select product and get rates "<SelectProduct>" and "<BundleSelection>" and "<Plan>" and "<Term>" and "<TermMiles>" and "<Deductible>" and "<RetailPrice>" and "<DealerCost>" and "<FirstServiceInterval>" and "<FinalServiceInterval>" and "<RegistrationCode>"
    And Verify Dealer Cost and Candian Taxation "<DealerCost>" and "<ExpDealerHST>" and "<ExpDealerGST>" and "<ExpDealerPST>" and "<ExpDealerQST>" and "<ExpDealerCostTotal>"
    And Verify Customer Cost and Candian Taxation "<CustomerCost>" and "<CustomerHST>" and "<CustomerGST>" and "<CustomerPST>" and "<CustomerQST>" and "<ExpTotalCustomerCost>"
    And Enter customer details "<isThisaBussiness>" and "<customerAgreementLanguage>" and "<BussinessName>" and "<FirstName>" and "<LastName>" and "<Address>" and "<PostalCode>" and "<PhoneNumber1>" and "<EmailAddress>" and "<Co-Signer>" and "<cos-First Name>" and "<cos-Last Name>" and "<cos-Address>" and "<cos-Postal Code>" and "<cos-Phone Number 1>" and "<cos-Email Address>" and "<SelectProduct>"
    And Enter vehicle purchase price and finance info "<SelectProduct>" and "<VehicleMSRP>" and "<FinanceAmount>" and  "<APR>" and "<GrossCapCost>" and "<Vehicleprice>"
    And Select Lienholder "<Lienholder>" and "<SelectProduct>"
    And Save the contract
    And Go to the summary page
    Then Logout out from the portal

    Examples: 
      | TestCase | Portal   | Language       | UserName | Dealer   | Password | Vin               | Make | Model | Trim | Year | Inservicedate | Province       | ContractPurchaseDate | Vehicle_Purchase | Vehicle_Purchase_Date | Vehicle_condtion | FinanceType | odometer | SelectProduct        | BundleSelection | Plan                                | Term | TermMiles | Deductible | DealerCost | ExpDealerHST | ExpDealerPST | ExpDealerGST | ExpDealerQST | ExpDealerCostTotal | CustomerCost | CustomerHST | CustomerPST | CustomerGST | CustomerQST | CustTotalCost | FirstServiceInterval | FinalServiceInterval | RegistrationCode | isThisaBussiness | FirstName | LastName  | customerAgreementLanguage | BussinessName | Address      | PostalCode | PhoneNumber1 | EmailAddress  | Co-Signer | cos-FirstName | cos-LastName | cos-Address | cos-PostalCode | cos-PhoneNumber1 | cos-EmailAddress | VehicleMSRP | FinanceAmount | APR | GrossCapCost | Vehicleprice | Lienholder |
      |       26 | Motorrad | English-Canada | moqaauto | MTC09220 | ******   | WB10C1504JZ316455 |      |       |      |      | 2021-05-25    | Alberta [ AB ] | 2021-05-25           | Yes              |                       | Pre-Owned        | CASH        |      111 | MOTORRAD CANADA VSC  |                 | VSC PLATINUM COVERAGE               |   60 |           |          0 |        720 |              |              |        36.00 |              |                    |         1720 |             |             |       86.00 |             |               |                      |                      |                  | No               | TESTQA026 | TESTQA026 | French-Canada             |               | TEST ADDRESS | T0M0A1     |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |       30000 |         10000 | 0.5 |              |        20500 |            |
      |       18 | BMW_MINI | English-Canada | bmqaauto | BMC06117 | ******   | WBA1F9C56GV509235 |      |       |      |      | 2021-05-25    | Alberta [ AB ] | 2021-05-25           | Yes              |                       | New              | CASH        |      111 | BMW CANADA VSC       |                 | VSC PLATINUM COVERAGE - IN WARRANTY |   72 |     80000 |          0 |       1500 |              |              |        75.00 |              |                    |         3000 |             |             |      150.00 |             |               |                      |                      |                  | No               | TESTQA018 | TESTQA018 | French-Canada             |               | TEST ADDRESS | T0M0A1     |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |       30000 |         10000 | 0.5 |              |        20500 |            |
      #|       19 | BMW_MINI | English-Canada | bmqaauto | BMC06117 | ******   | WBA7F2C58GG415625 |      |       |      |      | 2021-05-25    | Alberta [ AB ] | 2021-05-25           | Yes              |                       | CPO              | CASH        |      111 | BMW CANADA BASE CPO  |                 | BMW CANADA BASE CPO 7 SERIES PROMOTION |   72 |           |          0 |       1779 |              |              |        88.95 |              |                    |            0 |             |             |        0.00 |             |               |                      |                      |                  | No               | TESTQA019 | TESTQA019 | French-Canada             |               | TEST ADDRESS | T0M0A1     |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |       30000 |         10000 | 0.5 |              |        20500 |            |
      #|       20 | BMW_MINI | English-Canada | bmqaauto | BMC06117 | ******   | WBA7F2C58GG415625 |      |       |      |      | 2021-05-25    | Alberta [ AB ] | 2021-05-25           | Yes              |                       | CPO              | CASH        |      111 | BMW CANADA CPO       |                 | BMW CANADA CPO 7 SERIES PROMOTION      |   84 |           |          0 |       2459 |              |              |       122.95 |              |                    |         4959 |             |             |      247.95 |             |               |                      |                      |                  | No               | TESTQA020 | TESTQA019 | French-Canada             |               | TEST ADDRESS | T0M0A1     |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |       30000 |         10000 | 0.5 |              |        20500 |            |
      |       21 | BMW_MINI | English-Canada | bmqaauto | BMC06117 | ******   | WBA1F9C56GV509425 |      |       |      |      | 2021-05-25    | Alberta [ AB ] | 2021-05-25           | Yes              |                       | CPO              | CASH        |      111 | BMW CANADA BASE CPO  |                 | CPO BASE POWERTRAIN COVERAGE        |   60 |           |          0 |        649 |              |              |        32.45 |              |                    |            0 |             |             |        0.00 |             |               |                      |                      |                  | No               | TESTQA021 | TESTQA021 | French-Canada             |               | TEST ADDRESS | T0M0A1     |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |       30000 |         10000 | 0.5 |              |        20500 |            |
      #|       22 | BMW_MINI | English-Canada | bmqaauto | BMC06117 | ******   | WBA1F9C56GV509425 |      |       |      |      | 2021-05-25    | Alberta [ AB ] | 2021-05-25           | Yes              |                       | CPO              | CASH        |      111 | BMW CANADA CPO       |                 | CPO PLATINUM COVERAGE                  |   60 |           |          0 |        899 |              |              |        44.95 |              |                    |         3399 |             |             |      169.95 |             |               |                      |                      |                  | No               | TESTQA022 | TESTQA021 | French-Canada             |               | TEST ADDRESS | T0M0A1     |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |       30000 |         10000 | 0.5 |              |        20500 |            |
      |       23 | BMW_MINI | English-Canada | miqaauto | MNC09130 | ******   | WMWXP5C5XG2D22925 |      |       |      |      | 2021-05-25    | Alberta [ AB ] | 2021-05-25           | Yes              |                       | CPO              | CASH        |      111 | MINI CANADA BASE CPO |                 | CPO BASE POWERTRAIN COVERAGE        |   60 |           |          0 |        459 |              |              |        22.95 |              |                    |            0 |             |             |        0.00 |             |               |                      |                      |                  | No               | TESTQA023 | TESTQA023 | French-Canada             |               | TEST ADDRESS | T0M0A1     |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |       30000 |         10000 | 0.5 |              |        20500 |            |
      |       24 | BMW_MINI | English-Canada | miqaauto | MNC09130 | ******   | WMWXP5C5XG2D22925 |      |       |      |      | 2021-05-25    | Alberta [ AB ] | 2021-05-25           | Yes              |                       | CPO              | CASH        |      111 | MINI CANADA CPO      |                 | CPO PLATINUM COVERAGE               |   60 |    999999 |          0 |        799 |              |              |        39.95 |              |                    |         3299 |             |             |      164.95 |             |               |                      |                      |                  | No               | TESTQA024 | TESTQA023 | French-Canada             |               | TEST ADDRESS | T0M0A1     |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |       30000 |         10000 | 0.5 |              |        20500 |            |
      |       25 | BMW_MINI | English-Canada | miqaauto | MNC09130 | ******   | WMWXP5C5XG2D22095 |      |       |      |      | 2021-05-25    | Alberta [ AB ] | 2021-05-25           | Yes              |                       | New              | CASH        |    20001 | MINI CANADA VSC      |                 | VSC PLATINUM COVERAGE - IN WARRANTY |   72 |     80000 |          0 |       1370 |              |              |        68.50 |              |                    |         2370 |             |             |      118.50 |             |               |                      |                      |                  | No               | TESTQA025 | TESTQA025 | French-Canada             |               | TEST ADDRESS | T0M0A1     |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |       30000 |         10000 | 0.5 |              |        20500 |            |

  @SubmitContract_BMW-MINI_QA
  Scenario Outline: Save and Submit the New Contract
    Given Go to url with data as "<TestCase>" and "<Portal>" and "<Language>"and "<Dealer>"
    And Login as "<UserName>" and "<Password>" and "<Captcha>"
    When Click on add New eContract
    And Decode the VIN "<Vin>"
    And Enter contract purchase information "<Vin>" and "<Trim>" and "<Inservicedate>" and "<ContractPurchaseDate>" and "<Vehicle_Purchase>" and "<Vehicle_Purchase_Date>" and "<Vehicle_condtion>" and "<FinanceType>" and "<odometer>" and "<Province>"
    And Select product and get rates "<SelectProduct>" and "<BundleSelection>" and "<Plan>" and "<Term>" and "<TermMiles>" and "<Deductible>" and "<RetailPrice>" and "<DealerCost>" and "<FirstServiceInterval>" and "<FinalServiceInterval>" and "<RegistrationCode>"
    And Verify Dealer Cost and Candian Taxation "<DealerCost>" and "<ExpDealerHST>" and "<ExpDealerGST>" and "<ExpDealerPST>" and "<ExpDealerQST>" and "<ExpDealerCostTotal>"
    And Verify Customer Cost and Candian Taxation "<CustomerCost>" and "<CustomerHST>" and "<CustomerGST>" and "<CustomerPST>" and "<CustomerQST>" and "<ExpTotalCustomerCost>"
    And Enter customer details "<isThisaBussiness>" and "<customerAgreementLanguage>" and "<BussinessName>" and "<FirstName>" and "<LastName>" and "<Address>" and "<PostalCode>" and "<PhoneNumber1>" and "<EmailAddress>" and "<Co-Signer>" and "<cos-First Name>" and "<cos-Last Name>" and "<cos-Address>" and "<cos-Postal Code>" and "<cos-Phone Number 1>" and "<cos-Email Address>" and "<SelectProduct>"
    And Enter vehicle purchase price and finance info "<SelectProduct>" and "<VehicleMSRP>" and "<FinanceAmount>" and  "<APR>" and "<GrossCapCost>" and "<Vehicleprice>"
    And Select Lienholder "<Lienholder>" and "<SelectProduct>"
    And Save the contract
    And Go to the summary page
    And Click on Manage Saved eContracts
    And Select the contract with Last Name "<LastName>", VIN "<Vin>", Product "<SelectProduct>" and Portal "<Portal>"
    And Submit the contract
    Then Logout out from the portal

    Examples: 
      | TestCase | Portal   | Language       | UserName | Dealer   | Password | Vin               | Make | Model | Trim | Year | Inservicedate | Province       | ContractPurchaseDate | Vehicle_Purchase | Vehicle_Purchase_Date | Vehicle_condtion | FinanceType | odometer | SelectProduct        | BundleSelection | Plan                                   | Term | TermMiles | Deductible | DealerCost | ExpDealerHST | ExpDealerPST | ExpDealerGST | ExpDealerQST | ExpDealerCostTotal | CustomerCost | CustomerHST | CustomerPST | CustomerGST | CustomerQST | CustTotalCost | FirstServiceInterval | FinalServiceInterval | RegistrationCode | isThisaBussiness | FirstName | LastName  | customerAgreementLanguage | BussinessName | Address      | PostalCode | PhoneNumber1 | EmailAddress  | Co-Signer | cos-FirstName | cos-LastName | cos-Address | cos-PostalCode | cos-PhoneNumber1 | cos-EmailAddress | VehicleMSRP | FinanceAmount | APR | GrossCapCost | Vehicleprice | Lienholder |
      |       26 | Motorrad | English-Canada | moqaauto | MTC09220 | ******   | WB10C1504JZ316455 |      |       |      |      | 2021-05-25    | Alberta [ AB ] | 2021-05-25           | Yes              |                       | Pre-Owned        | CASH        |      111 | MOTORRAD CANADA VSC  |                 | VSC PLATINUM COVERAGE                  |   60 |           |          0 |        720 |              |              |        36.00 |              |                    |         1720 |             |             |       86.00 |             |               |                      |                      |                  | No               | TESTQA026 | TESTQA026 | French-Canada             |               | TEST ADDRESS | T0M0A1     |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |       30000 |         10000 | 0.5 |              |        20500 |            |
      |       18 | BMW_MINI | English-Canada | bmqaauto | BMC06117 | ******   | WBA1F9C56GV509235 |      |       |      |      | 2021-05-25    | Alberta [ AB ] | 2021-05-25           | Yes              |                       | New              | CASH        |      111 | BMW CANADA VSC       |                 | VSC PLATINUM COVERAGE - IN WARRANTY    |   72 |     80000 |          0 |       1500 |              |              |        75.00 |              |                    |         3000 |             |             |      150.00 |             |               |                      |                      |                  | No               | TESTQA018 | TESTQA018 | French-Canada             |               | TEST ADDRESS | T0M0A1     |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |       30000 |         10000 | 0.5 |              |        20500 |            |
      |       19 | BMW_MINI | English-Canada | bmqaauto | BMC06117 | ******   | WBA7F2C58GG415625 |      |       |      |      | 2021-05-25    | Alberta [ AB ] | 2021-05-25           | Yes              |                       | CPO              | CASH        |      111 | BMW CANADA BASE CPO  |                 | BMW CANADA BASE CPO 7 SERIES PROMOTION |   72 |           |          0 |       4779 |              |              |       238.95 |              |                    |            0 |             |             |        0.00 |             |               |                      |                      |                  | No               | TESTQA019 | TESTQA019 | French-Canada             |               | TEST ADDRESS | T0M0A1     |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |       30000 |         10000 | 0.5 |              |        20500 |            |
      |       20 | BMW_MINI | English-Canada | bmqaauto | BMC06117 | ******   | WBA7F2C58GG415625 |      |       |      |      | 2021-05-25    | Alberta [ AB ] | 2021-05-25           | Yes              |                       | CPO              | CASH        |      111 | BMW CANADA CPO       |                 | BMW CANADA CPO 7 SERIES PROMOTION      |   84 |           |          0 |       2459 |              |              |       122.95 |              |                    |         4459 |             |             |      222.95 |             |               |                      |                      |                  | No               | TESTQA020 | TESTQA019 | French-Canada             |               | TEST ADDRESS | T0M0A1     |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |       30000 |         10000 | 0.5 |              |        20500 |            |
      |       21 | BMW_MINI | English-Canada | bmqaauto | BMC06117 | ******   | WBA1F9C56GV509425 |      |       |      |      | 2021-05-25    | Alberta [ AB ] | 2021-05-25           | Yes              |                       | CPO              | CASH        |      111 | BMW CANADA BASE CPO  |                 | CPO BASE POWERTRAIN COVERAGE           |   60 |           |          0 |        649 |              |              |        32.45 |              |                    |            0 |             |             |        0.00 |             |               |                      |                      |                  | No               | TESTQA021 | TESTQA021 | French-Canada             |               | TEST ADDRESS | T0M0A1     |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |       30000 |         10000 | 0.5 |              |        20500 |            |
      |       22 | BMW_MINI | English-Canada | bmqaauto | BMC06117 | ******   | WBA1F9C56GV509425 |      |       |      |      | 2021-05-25    | Alberta [ AB ] | 2021-05-25           | Yes              |                       | CPO              | CASH        |      111 | BMW CANADA CPO       |                 | CPO PLATINUM COVERAGE                  |   60 |           |          0 |        899 |              |              |        44.95 |              |                    |         3399 |             |             |      169.95 |             |               |                      |                      |                  | No               | TESTQA022 | TESTQA021 | French-Canada             |               | TEST ADDRESS | T0M0A1     |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |       30000 |         10000 | 0.5 |              |        20500 |            |
      |       23 | BMW_MINI | English-Canada | miqaauto | MNC09130 | ******   | WMWXP5C5XG2D22925 |      |       |      |      | 2021-05-25    | Alberta [ AB ] | 2021-05-25           | Yes              |                       | CPO              | CASH        |      111 | MINI CANADA BASE CPO |                 | CPO BASE POWERTRAIN COVERAGE           |   60 |           |          0 |        459 |              |              |        22.95 |              |                    |            0 |             |             |        0.00 |             |               |                      |                      |                  | No               | TESTQA023 | TESTQA023 | French-Canada             |               | TEST ADDRESS | T0M0A1     |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |       30000 |         10000 | 0.5 |              |        20500 |            |
      |       24 | BMW_MINI | English-Canada | miqaauto | MNC09130 | ******   | WMWXP5C5XG2D22925 |      |       |      |      | 2021-05-25    | Alberta [ AB ] | 2021-05-25           | Yes              |                       | CPO              | CASH        |      111 | MINI CANADA CPO      |                 | CPO PLATINUM COVERAGE                  |   60 |    999999 |          0 |        799 |              |              |        39.95 |              |                    |         3299 |             |             |      164.95 |             |               |                      |                      |                  | No               | TESTQA024 | TESTQA023 | French-Canada             |               | TEST ADDRESS | T0M0A1     |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |       30000 |         10000 | 0.5 |              |        20500 |            |
      |       25 | BMW_MINI | English-Canada | miqaauto | MNC09130 | ******   | WMWXP5C5XG2D22095 |      |       |      |      | 2021-05-25    | Alberta [ AB ] | 2021-05-25           | Yes              |                       | New              | CASH        |    20001 | MINI CANADA VSC      |                 | VSC PLATINUM COVERAGE - IN WARRANTY    |   72 |     80000 |          0 |       1370 |              |              |        68.50 |              |                    |         2370 |             |             |      118.50 |             |               |                      |                      |                  | No               | TESTQA025 | TESTQA025 | French-Canada             |               | TEST ADDRESS | T0M0A1     |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |       30000 |         10000 | 0.5 |              |        20500 |            |
