Feature: To Test HONDA ACURA CANADA Portal Functionalities

  @SaveContract_HONDA-ACURA_QA
  Scenario Outline: Save Contract
    Given Go to url with data as "<TestCase>" and "<Portal>" and "<Language>"and "<Dealer>"
    And Login as "<UserName>" and "<Password>" and "<Captcha>"
    When Click on add New eContract
    And Decode the VIN "<Vin>"
    And Enter contract purchase information "<Vin>" and "<Trim>" and "<Inservicedate>" and "<ContractPurchaseDate>" and "<Vehicle_Purchase>" and "<Vehicle_Purchase_Date>" and "<Vehicle_condtion>" and "<FinanceType>" and "<odometer>" and "<Province>"
    And Select product and get rates "<SelectProduct>" and "<BundleSelection>" and "<Plan>" and "<Term>" and "<TermMiles>" and "<Deductible>" and "<RetailPrice>" and "<DealerCost>" and "<FirstServiceInterval>" and "<FinalServiceInterval>" and "<RegistrationCode>"
    And Verify Dealer Cost and Candian Taxation "<DealerCost>" and "<ExpDealerHST>" and "<ExpDealerGST>" and "<ExpDealerPST>" and "<ExpDealerQST>" and "<ExpDealerCostTotal>"
    And Verify Customer Cost and Candian Taxation "<CustomerCost>" and "<CustomerHST>" and "<CustomerGST>" and "<CustomerPST>" and "<CustomerQST>" and "<ExpTotalCustomerCost>"
    And Enter customer details "<isThisaBussiness>" and "<customerAgreementLanguage>" and "<BussinessName>" and "<FirstName>" and "<LastName>" and "<Address>" and "<PostalCode>" and "<PhoneNumber1>" and "<EmailAddress>" and "<Co-Signer>" and "<cos-First Name>" and "<cos-Last Name>" and "<cos-Address>" and "<cos-Postal Code>" and "<cos-Phone Number 1>" and "<cos-Email Address>" and "<SelectProduct>"
    And Enter vehicle purchase price and finance info "<SelectProduct>" and "<VehicleMSRP>" and "<FinanceAmount>" and  "<APR>" and "<GrossCapCost>" and "<Vehicleprice>"
    And Select Lienholder "<Lienholder>" and "<SelectProduct>"
    And Save the contract
    And Go to the summary page
    Then Logout out from the portal

    Examples: 
      | TestCase | Portal | Language       | UserName | Dealer   | Password | Vin               | Make | Model | Trim | Year | Inservicedate | Province       | ContractPurchaseDate | Vehicle_Purchase | Vehicle_Purchase_Date | Vehicle_condtion | FinanceType | odometer | SelectProduct     | BundleSelection | Plan              | Term | TermMiles | Deductible | DealerCost | ExpDealerHST | ExpDealerPST | ExpDealerGST | ExpDealerQST | ExpDealerCostTotal | CustomerCost | CustomerHST | CustomerPST | CustomerGST | CustomerQST | CustTotalCost | FirstServiceInterval | FinalServiceInterval | RegistrationCode | isThisaBussiness | FirstName  | LastName   | customerAgreementLanguage | BussinessName | Address      | PostalCode | PhoneNumber1 | EmailAddress  | Co-Signer | cos-FirstName | cos-LastName | cos-Address | cos-PostalCode | cos-PhoneNumber1 | cos-EmailAddress | VehicleMSRP | FinanceAmount | APR | GrossCapCost | Vehicleprice | Lienholder |
      |        1 | Honda  | English-Canada | hoqaauto | HOND1100 | ******   | 2HGFC2F81KH500257 |      |       |      |      | 2021-05-25    | Alberta [ AB ] | 2021-05-25           | Yes              |                       | New              | LEASE       |      111 | HONDA LEASE-GUARD |                 | HONDA LEASE-GUARD |   72 |           |            |        548 |              |              |        27.40 |              |                    |          898 |             |             |       44.90 |             |               |                      |                      |                  | No               | TESTHQA001 | TESTHQA001 | French-Canada             |               | TEST ADDRESS | T0M0A1     |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |             |               |     |              |              |            |
      |        2 | Honda  | English-Canada | hoqaauto | HOND1100 | ******   | 2HGFC2F81KH503456 |      |       |      |      | 2021-05-25    | Alberta [ AB ] | 2021-05-25           | Yes              |                       | Demo             | LEASE       |      111 | HONDA LEASE-GUARD |                 | HONDA LEASE-GUARD |   48 |           |            |        548 |              |              |        27.40 |              |                    |          898 |             |             |       44.90 |             |               |                      |                      |                  | No               | TESTHQA004 | TESTHQA004 | English-Canada            |               | TEST ADDRESS | T0M0A1     |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |             |               |     |              |              |            |
      |        3 | Acura  | English-Canada | acqaauto | ACUR2002 | ******   | 5J8TC2H32KL014567 |      |       |      |      | 2021-05-25    | Alberta [ AB ] | 2021-05-25           | Yes              |                       | Demo             | LEASE       |      121 | ACURA LEASE-GUARD |                 | ACURA LEASE-GUARD |   60 |           |            |        688 |              |              |        34.40 |              |                    |         1188 |             |             |       59.40 |             |               |                      |                      |                  | No               | TESTHQA005 | TESTHQA005 | English-Canada            |               | TEST ADDRESS | T0M0A1     |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |             |               |     |              |              |            |
      |        4 | Acura  | English-Canada | acqaauto | ACUR2002 | ******   | 5J8TC2H32KL010109 |      |       |      |      | 2021-05-25    | Alberta [ AB ] | 2021-05-25           | Yes              |                       | New              | LEASE       |      121 | ACURA LEASE-GUARD |                 | ACURA LEASE-GUARD |   60 |           |            |        688 |              |              |        34.40 |              |                    |         1188 |             |             |       59.40 |             |               |                      |                      |                  | No               | TESTHQA002 | TESTHQA002 | French-Canada             |               | TEST ADDRESS | T0M0A1     |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |             |               |     |              |              |            |
      |        5 | Acura  | English-Canada | acqaauto | ACUR2002 | ******   | 5J8TC2H32KL010110 |      |       |      |      | 2021-05-25    | Alberta [ AB ] | 2021-05-25           | Yes              |                       | New              | FINANCE     |      122 | ACURA PRECISION   |                 | PRECISION         |   60 |    120000 |            |        948 |              |              |        47.40 |              |                    |         1348 |             |             |       67.40 |             |               |                      |                      |                  | No               | TESTHQA003 | TESTHQA003 | French-Canada             |               | TEST ADDRESS | T0M0A1     |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |             |               |     |              |              |            |
      |        6 | Acura  | English-Canada | acqaauto | ACUR2002 | ******   | 5J8TC2H32KL098334 |      |       |      |      | 2021-05-25    | Alberta [ AB ] | 2021-05-25           | Yes              |                       | Demo             | CASH        |      122 | ACURA PRECISION   |                 | PRECISION         |   36 |     72000 |            |        738 |              |              |        36.90 |              |                    |         1138 |             |             |       56.90 |             |               |                      |                      |                  | No               | TESTHQA006 | TESTHQA006 | English-Canada            |               | TEST ADDRESS | T0M0A1     |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |             |               |     |              |              |            |

  @SubmitContract_HONDA-ACURA_QA
  Scenario Outline: Save and Submit the New Contract
    Given Go to url with data as "<TestCase>" and "<Portal>" and "<Language>"and "<Dealer>"
    And Login as "<UserName>" and "<Password>" and "<Captcha>"
    When Click on add New eContract
    And Decode the VIN "<Vin>"
    And Enter contract purchase information "<Vin>" and "<Trim>" and "<Inservicedate>" and "<ContractPurchaseDate>" and "<Vehicle_Purchase>" and "<Vehicle_Purchase_Date>" and "<Vehicle_condtion>" and "<FinanceType>" and "<odometer>" and "<Province>"
    And Select product and get rates "<SelectProduct>" and "<BundleSelection>" and "<Plan>" and "<Term>" and "<TermMiles>" and "<Deductible>" and "<RetailPrice>" and "<DealerCost>" and "<FirstServiceInterval>" and "<FinalServiceInterval>" and "<RegistrationCode>"
    And Verify Dealer Cost and Candian Taxation "<DealerCost>" and "<ExpDealerHST>" and "<ExpDealerGST>" and "<ExpDealerPST>" and "<ExpDealerQST>" and "<ExpDealerCostTotal>"
    And Verify Customer Cost and Candian Taxation "<CustomerCost>" and "<CustomerHST>" and "<CustomerGST>" and "<CustomerPST>" and "<CustomerQST>" and "<ExpTotalCustomerCost>"
    And Enter customer details "<isThisaBussiness>" and "<customerAgreementLanguage>" and "<BussinessName>" and "<FirstName>" and "<LastName>" and "<Address>" and "<PostalCode>" and "<PhoneNumber1>" and "<EmailAddress>" and "<Co-Signer>" and "<cos-First Name>" and "<cos-Last Name>" and "<cos-Address>" and "<cos-Postal Code>" and "<cos-Phone Number 1>" and "<cos-Email Address>" and "<SelectProduct>"
    And Enter vehicle purchase price and finance info "<SelectProduct>" and "<VehicleMSRP>" and "<FinanceAmount>" and  "<APR>" and "<GrossCapCost>" and "<Vehicleprice>"
    And Select Lienholder "<Lienholder>" and "<SelectProduct>"
    And Save the contract
    And Go to the summary page
    And Click on Manage Saved eContracts
    And Select the contract with Last Name "<LastName>", VIN "<Vin>", Product "<SelectProduct>" and Portal "<Portal>"
    And Submit the contract
    Then Logout out from the portal

    Examples: 
      | TestCase | Portal | Language       | UserName | Dealer   | Password | Vin               | Make | Model | Trim | Year | Inservicedate | Province       | ContractPurchaseDate | Vehicle_Purchase | Vehicle_Purchase_Date | Vehicle_condtion | FinanceType | odometer | SelectProduct     | BundleSelection | Plan              | Term | TermMiles | Deductible | DealerCost | ExpDealerHST | ExpDealerPST | ExpDealerGST | ExpDealerQST | ExpDealerCostTotal | CustomerCost | CustomerHST | CustomerPST | CustomerGST | CustomerQST | CustTotalCost | FirstServiceInterval | FinalServiceInterval | RegistrationCode | isThisaBussiness | FirstName  | LastName   | customerAgreementLanguage | BussinessName | Address      | PostalCode | PhoneNumber1 | EmailAddress  | Co-Signer | cos-FirstName | cos-LastName | cos-Address | cos-PostalCode | cos-PhoneNumber1 | cos-EmailAddress | VehicleMSRP | FinanceAmount | APR | GrossCapCost | Vehicleprice | Lienholder |
      |        1 | Honda  | English-Canada | hoqaauto | HOND1100 | ******   | 2HGFC2F81KH500257 |      |       |      |      | 2021-05-25    | Alberta [ AB ] | 2021-05-25           | Yes              |                       | New              | LEASE       |      111 | HONDA LEASE-GUARD |                 | HONDA LEASE-GUARD |   72 |           |            |        548 |              |              |        27.40 |              |                    |          898 |             |             |       44.90 |             |               |                      |                      |                  | No               | TESTHQA001 | TESTHQA001 | French-Canada             |               | TEST ADDRESS | T0M0A1     |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |             |               |     |              |              |            |
      |        2 | Acura  | English-Canada | acqaauto | ACUR2002 | ******   | 5J8TC2H32KL010109 |      |       |      |      | 2021-05-25    | Alberta [ AB ] | 2021-05-25           | Yes              |                       | New              | LEASE       |      121 | ACURA LEASE-GUARD |                 | ACURA LEASE-GUARD |   60 |           |            |        688 |              |              |        34.40 |              |                    |         1188 |             |             |       59.40 |             |               |                      |                      |                  | No               | TESTHQA002 | TESTHQA002 | French-Canada             |               | TEST ADDRESS | T0M0A1     |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |             |               |     |              |              |            |
      |        3 | Acura  | English-Canada | acqaauto | ACUR2002 | ******   | 5J8TC2H32KL010110 |      |       |      |      | 2021-05-25    | Alberta [ AB ] | 2021-05-25           | Yes              |                       | New              | FINANCE     |      122 | ACURA PRECISION   |                 | ACURA PRECISION   |   60 |    120000 |            |        948 |              |              |        47.40 |              |                    |         1198 |             |             |       59.90 |             |               |                      |                      |                  | No               | TESTHQA003 | TESTHQA003 | French-Canada             |               | TEST ADDRESS | T0M0A1     |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |             |               |     |              |              |            |
      |        4 | Honda  | English-Canada | hoqaauto | HOND1100 | ******   | 2HGFC2F81KH503456 |      |       |      |      | 2021-05-25    | Alberta [ AB ] | 2021-05-25           | Yes              |                       | Demo             | LEASE       |      111 | HONDA LEASE-GUARD |                 | HONDA LEASE-GUARD |   48 |           |            |        548 |              |              |        27.40 |              |                    |          898 |             |             |       44.90 |             |               |                      |                      |                  | No               | TESTHQA004 | TESTHQA004 | English-Canada            |               | TEST ADDRESS | T0M0A1     |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |             |               |     |              |              |            |
      |        5 | Acura  | English-Canada | acqaauto | ACUR2002 | ******   | 5J8TC2H32KL014567 |      |       |      |      | 2021-05-25    | Alberta [ AB ] | 2021-05-25           | Yes              |                       | Demo             | LEASE       |      121 | ACURA LEASE-GUARD |                 | ACURA LEASE-GUARD |   60 |           |            |        688 |              |              |        34.40 |              |                    |         1188 |             |             |       59.40 |             |               |                      |                      |                  | No               | TESTHQA005 | TESTHQA005 | English-Canada            |               | TEST ADDRESS | T0M0A1     |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |             |               |     |              |              |            |
      |        6 | Acura  | English-Canada | acqaauto | ACUR2002 | ******   | 5J8TC2H32KL098334 |      |       |      |      | 2021-05-25    | Alberta [ AB ] | 2021-05-25           | Yes              |                       | Demo             | CASH        |      122 | ACURA PRECISION   |                 | ACURA PRECISION   |   36 |     72000 |            |        708 |              |              |        35.40 |              |                    |          958 |             |             |       47.90 |             |               |                      |                      |                  | No               | TESTHQA006 | TESTHQA006 | English-Canada            |               | TEST ADDRESS | T0M0A1     |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |             |               |     |              |              |            |
