Feature: To Test Penske Functionality

  @SaveContract_Penske_QA
  Scenario Outline: Add a New Contract
    Given Go to url with data as "<TestCase>" and "<Portal>" and "<Language>"and "<Dealer>"
    And Login as "<UserName>" and "<Password>" and "<Captcha>"
    When Click on add New eContract
    And Decode the VIN "<Vin>"
    And Enter contract purchase information "<Vin>" and "<Trim>" and "<Inservicedate>" and "<ContractPurchaseDate>" and "<Vehicle_Purchase>" and "<Vehicle_Purchase_Date>" and "<Vehicle_condtion>" and "<FinanceType>" and "<odometer>" and "<Province>"
    And Select product and get rates "<SelectProduct>" and "<BundleSelection>" and "<Plan>" and "<Term>" and "<TermMiles>" and "<Deductible>" and "<RetailPrice>" and "<DealerCost>" and "<FirstServiceInterval>" and "<FinalServiceInterval>" and "<RegistrationCode>"
    And Verify Dealer Cost and Retail Price "<DealerCost>" and "<RetailPrice>"
    And Enter customer details "<isThisaBussiness>" and "<customerAgreementLanguage>" and "<BussinessName>" and "<FirstName>" and "<LastName>" and "<Address>" and "<PostalCode>" and "<PhoneNumber1>" and "<EmailAddress>" and "<Co-Signer>" and "<cos-First Name>" and "<cos-Last Name>" and "<cos-Address>" and "<cos-Postal Code>" and "<cos-Phone Number 1>" and "<cos-Email Address>" and "<SelectProduct>"
    And Enter vehicle purchase price and finance info "<SelectProduct>" and "<VehicleMSRP>" and "<FinanceAmount>" and  "<APR>" and "<GrossCapCost>" and "<Vehicleprice>"
    And Select Lienholder "<Lienholder>" and "<SelectProduct>"
    And Save the contract
    And Go to the summary page
    Then Logout out from the portal

    Examples: 
      | TestCase | Portal | Language   | Dealer   | UserName | Password | Captcha | Vin               | Make | Model | Trim | Year | Inservicedate | ContractPurchaseDate | Vehicle_Purchase | Vehicle_Purchase_Date | Vehicle_condtion | FinanceType | odometer | SelectProduct                    | BundleSelection               | Plan | Term | TermMiles | Deductible | FirstServiceInterval | FinalServiceInterval | RegistrationCode | DealerCost | RetailPrice | isThisaBussiness | BussinessName | FirstName | LastName  | Address    | PostalCode | PhoneNumber1 | EmailAddress  | Co-Signer | cos-FirstName | cos-LastName | cos-Address | cos-PostalCode | cos-PhoneNumber1 | cos-EmailAddress | VehicleMSRP | FinanceAmount | APR | GrossCapCost | Vehicleprice | Lienholder |
      |       71 | Penske | English-US | PAG45855 | pkqaauto | ******   |         | ZFF73SKA6G0215312 |      |       |      | 2016 | 2021-05-25    | 2021-05-25           | Yes              |                       | NEW              | FINANCE     |     2000 | PENSKE MULTI-COVERAGE PROTECTION | BRONZE BUNDLE WITH COSMETIC   |      |   12 |           |          0 |                      |                      |                  |       1765 |         280 | No               |               | TESTQA071 | TESTQA071 | 123 STREET |      90013 |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |       10000 |         15000 | 0.5 |        10000 |        25000 |            |
      |       72 | Penske | English-US | PAG45855 | pkqaauto | ******   |         | ZFF77XJA5G0217623 |      |       |      | 2016 | 2021-05-25    | 2021-05-25           | Yes              |                       | NEW              | FINANCE     |     2000 | PENSKE MULTI-COVERAGE PROTECTION | GOLD BUNDLE WITH COSMETIC     |      |   12 |           |          0 |                      |                      |                  |       2100 |         280 | No               |               | TESTQA072 | TESTQA072 | 123 STREET |      90013 |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |       10000 |         15000 | 0.5 |        10000 |        25000 |            |
      |       73 | Penske | English-US | PAG45855 | pkqaauto | ******   |         | ZFF77XJA7G0214835 |      |       |      | 2016 | 2021-05-25    | 2021-05-25           | Yes              |                       | NEW              | FINANCE     |     2000 | PENSKE MULTI-COVERAGE PROTECTION | PLATINUM BUNDLE WITH COSMETIC |      |   12 |           |          0 |                      |                      |                  |       2435 |         280 | No               |               | TESTQA073 | TESTQA073 | 123 STREET |      90013 |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |       10000 |         15000 | 0.5 |        10000 |        25000 |            |
      |       74 | Penske | English-US | PAG45855 | pkqaauto | ******   |         | ZFF79ALA3G0217044 |      |       |      | 2016 | 2021-05-25    | 2021-05-25           | Yes              |                       | NEW              | FINANCE     |     2000 | PENSKE MULTI-COVERAGE PROTECTION | X                             |      |   12 |           |          0 |                      |                      |                  |        410 |         280 | No               |               | TESTQA074 | TESTQA074 | 123 STREET |      90013 |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |       10000 |         15000 | 0.5 |        10000 |        25000 |            |
      |       75 | Penske | English-US | PAG45855 | pkqaauto | ******   |         | ZFF79ALA7G0215654 |      |       |      | 2016 | 2021-05-25    | 2021-05-25           | Yes              |                       | NEW              | FINANCE     |     2000 | PENSKE MULTI-COVERAGE PROTECTION | D                             |      |   12 |           |          0 |                      |                      |                  |        470 |         280 | No               |               | TESTQA075 | TESTQA075 | 123 STREET |      90013 |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |       10000 |         15000 | 0.5 |        10000 |        25000 |            |
      |       76 | Penske | English-US | PAG45855 | pkqaauto | ******   |         | ZFF79ALA8G0215464 |      |       |      | 2016 | 2021-05-25    | 2021-05-25           | Yes              |                       | NEW              | FINANCE     |     2000 | PENSKE MULTI-COVERAGE PROTECTION | P                             |      |   12 |           |          0 |                      |                      |                  |       1325 |         280 | No               |               | TESTQA076 | TESTQA076 | 123 STREET |      90013 |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |       10000 |         15000 | 0.5 |        10000 |        25000 |            |
      |       77 | Penske | English-US | PAG45855 | pkqaauto | ******   |         | ZFF79ALA8G0216374 |      |       |      | 2016 | 2021-05-25    | 2021-05-25           | Yes              |                       | NEW              | FINANCE     |     2000 | PENSKE MULTI-COVERAGE PROTECTION | K                             |      |   12 |           |          0 |                      |                      |                  |        440 |         280 | No               |               | TESTQA077 | TESTQA077 | 123 STREET |      90013 |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |       10000 |         15000 | 0.5 |        10000 |        25000 |            |

  @SubmitContract_Penske_QA
  Scenario Outline: Save and Submit the New Contract
    Given Go to url with data as "<TestCase>" and "<Portal>" and "<Language>"and "<Dealer>"
    And Login as "<UserName>" and "<Password>" and "<Captcha>"
    When Click on add New eContract
    And Decode the VIN "<Vin>"
    And Enter contract purchase information "<Vin>" and "<Trim>" and "<Inservicedate>" and "<ContractPurchaseDate>" and "<Vehicle_Purchase>" and "<Vehicle_Purchase_Date>" and "<Vehicle_condtion>" and "<FinanceType>" and "<odometer>" and "<Province>"
    And Select product and get rates "<SelectProduct>" and "<BundleSelection>" and "<Plan>" and "<Term>" and "<TermMiles>" and "<Deductible>" and "<RetailPrice>" and "<DealerCost>" and "<FirstServiceInterval>" and "<FinalServiceInterval>" and "<RegistrationCode>"
    And Verify Dealer Cost and Retail Price "<DealerCost>" and "<RetailPrice>"
    And Enter customer details "<isThisaBussiness>" and "<customerAgreementLanguage>" and "<BussinessName>" and "<FirstName>" and "<LastName>" and "<Address>" and "<PostalCode>" and "<PhoneNumber1>" and "<EmailAddress>" and "<Co-Signer>" and "<cos-First Name>" and "<cos-Last Name>" and "<cos-Address>" and "<cos-Postal Code>" and "<cos-Phone Number 1>" and "<cos-Email Address>" and "<SelectProduct>"
    And Enter vehicle purchase price and finance info "<SelectProduct>" and "<VehicleMSRP>" and "<FinanceAmount>" and  "<APR>" and "<GrossCapCost>" and "<Vehicleprice>"
    And Select Lienholder "<Lienholder>" and "<SelectProduct>"
    And Save the contract
    And Go to the summary page
    And Click on Manage Saved eContracts
    And Select the contract with Last Name "<LastName>", VIN "<Vin>", Product "<SelectProduct>" and Portal "<Portal>"
    And Submit the contract
    Then Logout out from the portal

    Examples: 
      | TestCase | Portal | Language   | Dealer   | UserName | Password | Captcha | Vin               | Make | Model | Trim | Year | Inservicedate | ContractPurchaseDate | Vehicle_Purchase | Vehicle_Purchase_Date | Vehicle_condtion | FinanceType | odometer | SelectProduct                    | BundleSelection               | Plan | Term | TermMiles | Deductible | FirstServiceInterval | FinalServiceInterval | RegistrationCode | DealerCost | RetailPrice | isThisaBussiness | BussinessName | FirstName | LastName  | Address    | PostalCode | PhoneNumber1 | EmailAddress  | Co-Signer | cos-FirstName | cos-LastName | cos-Address | cos-PostalCode | cos-PhoneNumber1 | cos-EmailAddress | VehicleMSRP | FinanceAmount | APR | GrossCapCost | Vehicleprice | Lienholder |
      |       71 | Penske | English-US | PAG45855 | pkqaauto | ******   |         | ZFF73SKA6G0215312 |      |       |      | 2016 | 2017-06-27    | 2019-12-18           | Yes              |                       | NEW              | FINANCE     |     2000 | PENSKE MULTI-COVERAGE PROTECTION | BRONZE BUNDLE WITH COSMETIC   |      |   12 |           |          0 |                      |                      |                  |       1765 |         280 | No               |               | TESTQA071 | TESTQA071 | 123 STREET |      90013 |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |       10000 |         15000 | 0.5 |        10000 |        25000 |            |
      |       72 | Penske | English-US | PAG45855 | pkqaauto | ******   |         | ZFF77XJA5G0217623 |      |       |      | 2016 | 2017-06-27    | 2019-12-18           | Yes              |                       | NEW              | FINANCE     |     2000 | PENSKE MULTI-COVERAGE PROTECTION | GOLD BUNDLE WITH COSMETIC     |      |   12 |           |          0 |                      |                      |                  |       2100 |         280 | No               |               | TESTQA072 | TESTQA072 | 123 STREET |      90013 |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |       10000 |         15000 | 0.5 |        10000 |        25000 |            |
      |       73 | Penske | English-US | PAG45855 | pkqaauto | ******   |         | ZFF77XJA7G0214835 |      |       |      | 2016 | 2017-06-27    | 2019-12-18           | Yes              |                       | NEW              | FINANCE     |     2000 | PENSKE MULTI-COVERAGE PROTECTION | PLATINUM BUNDLE WITH COSMETIC |      |   12 |           |          0 |                      |                      |                  |       2435 |         280 | No               |               | TESTQA073 | TESTQA073 | 123 STREET |      90013 |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |       10000 |         15000 | 0.5 |        10000 |        25000 |            |
      |       74 | Penske | English-US | PAG45855 | pkqaauto | ******   |         | ZFF79ALA3G0217044 |      |       |      | 2016 | 2017-06-27    | 2019-12-18           | Yes              |                       | NEW              | FINANCE     |     2000 | PENSKE MULTI-COVERAGE PROTECTION | X                             |      |   12 |           |          0 |                      |                      |                  |        410 |         280 | No               |               | TESTQA074 | TESTQA074 | 123 STREET |      90013 |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |       10000 |         15000 | 0.5 |        10000 |        25000 |            |
      |       75 | Penske | English-US | PAG45855 | pkqaauto | ******   |         | ZFF79ALA7G0215654 |      |       |      | 2016 | 2017-06-27    | 2019-12-18           | Yes              |                       | NEW              | FINANCE     |     2000 | PENSKE MULTI-COVERAGE PROTECTION | D                             |      |   12 |           |          0 |                      |                      |                  |        470 |         280 | No               |               | TESTQA075 | TESTQA075 | 123 STREET |      90013 |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |       10000 |         15000 | 0.5 |        10000 |        25000 |            |
      |       76 | Penske | English-US | PAG45855 | pkqaauto | ******   |         | ZFF79ALA8G0215464 |      |       |      | 2016 | 2017-06-27    | 2019-12-18           | Yes              |                       | NEW              | FINANCE     |     2000 | PENSKE MULTI-COVERAGE PROTECTION | P                             |      |   12 |           |          0 |                      |                      |                  |       1325 |         280 | No               |               | TESTQA076 | TESTQA076 | 123 STREET |      90013 |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |       10000 |         15000 | 0.5 |        10000 |        25000 |            |
      |       77 | Penske | English-US | PAG45855 | pkqaauto | ******   |         | ZFF79ALA8G0216374 |      |       |      | 2016 | 2017-06-27    | 2019-12-18           | Yes              |                       | NEW              | FINANCE     |     2000 | PENSKE MULTI-COVERAGE PROTECTION | K                             |      |   12 |           |          0 |                      |                      |                  |        440 |         280 | No               |               | TESTQA077 | TESTQA077 | 123 STREET |      90013 |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |       10000 |         15000 | 0.5 |        10000 |        25000 |            |
