Feature: To Test RollsRoyce Portal Functionalities

  @SaveContract_RollsRoyce_QA
  Scenario Outline: Add a New Contract
    Given Go to url with data as "<TestCase>" and "<Portal>" and "<Language>"and "<Dealer>"
    And Login as "<UserName>" and "<Password>" and "<Captcha>"
    When Click on add New eContract
    And Decode the VIN "<Vin>"
    And Enter contract purchase information "<Vin>" and "<Trim>" and "<Inservicedate>" and "<ContractPurchaseDate>" and "<Vehicle_Purchase>" and "<Vehicle_Purchase_Date>" and "<Vehicle_condtion>" and "<FinanceType>" and "<odometer>" and "<Province>"
    And Select product and get rates "<SelectProduct>" and "<BundleSelection>" and "<Plan>" and "<Term>" and "<TermMiles>" and "<Deductible>" and "<RetailPrice>" and "<DealerCost>" and "<FirstServiceInterval>" and "<FinalServiceInterval>" and "<RegistrationCode>"
    And Verify Dealer Cost and Retail Price "<DealerCost>" and "<RetailPrice>"
    And Enter customer details "<isThisaBussiness>" and "<customerAgreementLanguage>" and "<BussinessName>" and "<FirstName>" and "<LastName>" and "<Address>" and "<PostalCode>" and "<PhoneNumber1>" and "<EmailAddress>" and "<Co-Signer>" and "<cos-First Name>" and "<cos-Last Name>" and "<cos-Address>" and "<cos-Postal Code>" and "<cos-Phone Number 1>" and "<cos-Email Address>" and "<SelectProduct>"
    And Enter vehicle purchase price and finance info "<SelectProduct>" and "<VehicleMSRP>" and "<FinanceAmount>" and  "<APR>" and "<GrossCapCost>" and "<Vehicleprice>"
    And Select Lienholder "<Lienholder>" and "<SelectProduct>"
    And Save the contract
    And Go to the summary page
    Then Logout out from the portal

    Examples: 
      | TestCase | Portal     | Language | Dealer   | UserName | Password | Captcha | Vin               | Make | Model | Trim | Year | Inservicedate | ContractPurchaseDate | Vehicle_Purchase | Vehicle_Purchase_Date | Vehicle_condtion | FinanceType | odometer | SelectProduct           | BundleSelection | Plan                 | Term | TermMiles | Deductible | FirstServiceInterval | FinalServiceInterval | RegistrationCode | DealerCost | RetailPrice | isThisaBussiness | BussinessName | FirstName | LastName  | Address    | PostalCode | PhoneNumber1 | EmailAddress  | Co-Signer | cos-FirstName | cos-LastName | cos-Address | cos-PostalCode | cos-PhoneNumber1 | cos-EmailAddress | VehicleMSRP | FinanceAmount | APR | GrossCapCost | Vehicleprice | Lienholder                   |
      |       70 | RollsRoyce |          | R5054115 | rrqaauto | ******   |         | SCA665C51GUX86012 |      |       |      |      | 2021-05-25    | 2021-05-25           | Yes              |                       | New              | FINANCE     |      100 | RR GAP PROTECTION       |                 | GAP PROTECTION       |   56 |           |          0 |                      |                      |                  |        550 |         600 | No               |               | TESTQA038 | TESTQA038 | 123 STREET |      30328 |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |       10000 |         15000 | 0.5 |              |              | BMW Financial Service NA LLC |
      |       71 | RollsRoyce |          | R5054115 | rrqaauto | ******   |         | SCA665C51GUX86012 |      |       |      |      | 2021-05-25    | 2021-05-25           | Yes              |                       | New              | LEASE       |      100 | RR LEASE-END PROTECTION |                 | LEASE-END PROTECTION |   45 |           |          0 |                      |                      |                  |       2140 |        2500 | No               |               | TESTQA039 | TESTQA039 | 123 STREET |      30328 |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |       10000 |               |     |        10000 |              | BMW Financial Service NA LLC |
      |       72 | RollsRoyce |          | R5054115 | rrqaauto | ******   |         | SCA665C51GUX86012 |      |       |      |      | 2021-05-25    | 2021-05-25           | Yes              |                       | New              | FINANCE     |      100 | RR MULTI-COVERAGE       | GB              |                      |   56 |           |        100 |                      |                      |                  |       2873 |        3300 | No               |               | TESTQA040 | TESTQA040 | 123 STREET |      30328 |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |       10000 |         15000 | 0.5 |        10000 |        25000 |                              |

  @SubmitContract_RollsRoyce_QA
  Scenario Outline: Save and Submit the New Contract
    Given Go to url with data as "<TestCase>" and "<Portal>" and "<Language>"and "<Dealer>"
    And Login as "<UserName>" and "<Password>" and "<Captcha>"
    When Click on add New eContract
    And Decode the VIN "<Vin>"
    And Enter contract purchase information "<Vin>" and "<Trim>" and "<Inservicedate>" and "<ContractPurchaseDate>" and "<Vehicle_Purchase>" and "<Vehicle_Purchase_Date>" and "<Vehicle_condtion>" and "<FinanceType>" and "<odometer>" and "<Province>"
    And Select product and get rates "<SelectProduct>" and "<BundleSelection>" and "<Plan>" and "<Term>" and "<TermMiles>" and "<Deductible>" and "<RetailPrice>" and "<DealerCost>" and "<FirstServiceInterval>" and "<FinalServiceInterval>" and "<RegistrationCode>"
    And Verify Dealer Cost and Retail Price "<DealerCost>" and "<RetailPrice>"
    And Enter customer details "<isThisaBussiness>" and "<customerAgreementLanguage>" and "<BussinessName>" and "<FirstName>" and "<LastName>" and "<Address>" and "<PostalCode>" and "<PhoneNumber1>" and "<EmailAddress>" and "<Co-Signer>" and "<cos-First Name>" and "<cos-Last Name>" and "<cos-Address>" and "<cos-Postal Code>" and "<cos-Phone Number 1>" and "<cos-Email Address>" and "<SelectProduct>"
    And Enter vehicle purchase price and finance info "<SelectProduct>" and "<VehicleMSRP>" and "<FinanceAmount>" and  "<APR>" and "<GrossCapCost>" and "<Vehicleprice>"
    And Select Lienholder "<Lienholder>" and "<SelectProduct>"
    And Save the contract
    And Go to the summary page
    And Click on Manage Saved eContracts
    And Select the contract with Last Name "<LastName>", VIN "<Vin>", Product "<SelectProduct>" and Portal "<Portal>"
    And Submit the contract
    Then Logout out from the portal

    Examples: 
      | TestCase | Portal     | Language | Dealer   | UserName | Password | Captcha | Vin               | Make | Model | Trim | Year | Inservicedate | ContractPurchaseDate | Vehicle_Purchase | Vehicle_Purchase_Date | Vehicle_condtion | FinanceType | odometer | SelectProduct           | BundleSelection | Plan                 | Term | TermMiles | Deductible | FirstServiceInterval | FinalServiceInterval | RegistrationCode | DealerCost | RetailPrice | isThisaBussiness | BussinessName | FirstName | LastName     | Address    | PostalCode | PhoneNumber1 | EmailAddress  | Co-Signer | cos-FirstName | cos-LastName | cos-Address | cos-PostalCode | cos-PhoneNumber1 | cos-EmailAddress | VehicleMSRP | FinanceAmount | APR | GrossCapCost | Vehicleprice | Lienholder                   |
      |       70 | RollsRoyce |          | R5054115 | rrqaauto | ******   |         | SCA665C51GUX86012 |      |       |      |      | 2018-10-21    | 2019-12-18           | Yes              |                       | New              | FINANCE     |      100 | RR GAP PROTECTION       |                 | GAP PROTECTION       |   56 |           |          0 |                      |                      |                  |        550 |         600 | No               |               | TESTQA038 | TESTRASQA038 | 123 STREET |      30328 |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |       10000 |         15000 | 0.5 |              |              | BMW Financial Service NA LLC |
      |       71 | RollsRoyce |          | R5054115 | rrqaauto | ******   |         | SCA665C51GUX86012 |      |       |      |      | 2018-10-21    | 2019-12-18           | Yes              |                       | New              | LEASE       |      100 | RR LEASE-END PROTECTION |                 | LEASE-END PROTECTION |   45 |           |          0 |                      |                      |                  |       2140 |        2500 | No               |               | TESTQA039 | TESTRASQA039 | 123 STREET |      30328 |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |       10000 |               |     |        10000 |              | BMW Financial Service NA LLC |
      |       72 | RollsRoyce |          | R5054115 | rrqaauto | ******   |         | SCA665C51GUX86012 |      |       |      |      | 2018-10-21    | 2019-12-18           | Yes              |                       | New              | FINANCE     |      100 | RR MULTI-COVERAGE       | GB              |                      |   56 |           |        100 |                      |                      |                  |       2873 |        3300 | No               |               | TESTQA040 | TESTRASQA040 | 123 STREET |      30328 |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |       10000 |         15000 | 0.5 |        10000 |        25000 |                              |
