Feature: To Test HD CAN Portal Functionalities

  @SaveContract_HD_CA_PROD
  Scenario Outline: Save Contract
    Given Go to url with data as "<TestCase>" and "<Portal>" and "<Language>"and "<Dealer>"
    And Login as "<UserName>" and "<Password>" and "<Captcha>"
    When Click on add New eContract
    And Decode the VIN "<Vin>"
    And Enter contract purchase information "<Vin>" and "<Trim>" and "<Inservicedate>" and "<ContractPurchaseDate>" and "<Vehicle_Purchase>" and "<Vehicle_Purchase_Date>" and "<Vehicle_condtion>" and "<FinanceType>" and "<odometer>" and "<Province>"
    And Select product and get rates "<SelectProduct>" and "<BundleSelection>" and "<Plan>" and "<Term>" and "<TermMiles>" and "<Deductible>" and "<RetailPrice>" and "<DealerCost>" and "<FirstServiceInterval>" and "<FinalServiceInterval>" and "<RegistrationCode>"
    And Verify Dealer Cost and Candian Taxation "<DealerCost>" and "<ExpDealerHST>" and "<ExpDealerGST>" and "<ExpDealerPST>" and "<ExpDealerQST>" and "<ExpDealerCostTotal>"
    And Verify Customer Cost and Candian Taxation "<CustomerCost>" and "<CustomerHST>" and "<CustomerGST>" and "<CustomerPST>" and "<CustomerQST>" and "<ExpTotalCustomerCost>"
    And Enter customer details "<isThisaBussiness>" and "<customerAgreementLanguage>" and "<BussinessName>" and "<FirstName>" and "<LastName>" and "<Address>" and "<PostalCode>" and "<PhoneNumber1>" and "<EmailAddress>" and "<Co-Signer>" and "<cos-First Name>" and "<cos-Last Name>" and "<cos-Address>" and "<cos-Postal Code>" and "<cos-Phone Number 1>" and "<cos-Email Address>" and "<SelectProduct>"
    And Enter vehicle purchase price and finance info "<SelectProduct>" and "<VehicleMSRP>" and "<FinanceAmount>" and  "<APR>" and "<GrossCapCost>" and "<Vehicleprice>"
    And Select Lienholder "<Lienholder>" and "<SelectProduct>"
    And Save the contract
    And Go to the summary page
    Then Logout out from the portal

    Examples: 
      | TestCase | Portal        | Language       | UserName | Dealer   | Password | Vin               | Make            | Model     | Trim      | Year | Inservicedate | Province       | ContractPurchaseDate | Vehicle_Purchase | Vehicle_Purchase_Date | Vehicle_condtion | FinanceType | odometer | SelectProduct                       | BundleSelection | Plan             | Term | TermMiles | Deductible | DealerCost | ExpDealerHST | ExpDealerPST | ExpDealerGST | ExpDealerQST | ExpDealerCostTotal | CustomerCost | CustomerHST | CustomerPST | CustomerGST | CustomerQST | CustTotalCost | FirstServiceInterval | FinalServiceInterval | RegistrationCode | isThisaBussiness | FirstName | LastName  | customerAgreementLanguage | BussinessName | Address    | PostalCode | PhoneNumber1 | EmailAddress  | Co-Signer | cos-FirstName | cos-LastName | cos-Address | cos-PostalCode | cos-PhoneNumber1 | cos-EmailAddress | VehicleMSRP | FinanceAmount | APR | GrossCapCost | Vehicleprice | Lienholder |
      |        1 | Harley_Canada | English-Canada | hdqaauto | 0HD50020 | ******   | 1HD1JRV10FB020635 | HARLEY-DAVIDSON | SPORTSTER | SUPERFLOW | 2016 | 2020-12-14    | Alberta [ AB ] | 2020-12-14           | Yes              |                       | New              | CASH        |     1000 | HARLEY-DAVIDSON PLANNED MAINTENANCE |                 |                  |      |           |          0 |        835 |              |              |        41.75 |              |             876.75 |          800 |             |             |          35 |             |           835 | 24000 KILOMETERS     | 32000 KILOMETERS     |                  | No               | TESTQA015 | TESTQA015 | English-Canada            |               | 123 STREET | V1Z 1A3    |   5646556564 | test@test.com | No        |               |              |             |                |                  |                  |             |               |     |              |              |            |
      |        2 | Harley_Canada | English-Canada | hdqaauto | 0HD50020 | ******   | 5HD2XAEB4LB800116 | HARLEY-DAVIDSON | LIVEWIRE  | BASE      | 2020 | 2020-12-14    | Alberta [ AB ] | 2020-12-14           | Yes              |                       | Pre-Owned        | CASH        |       11 | HARLEY-DAVIDSON PLANNED MAINTENANCE |                 |                  |      |           |          0 |       1469 |              |              |        73.45 |              |            1542.45 |         1500 |             |             |          55 |             |        1555.0 | 48000 KILOMETERS     | 80000 KILOMETERS     |                  | No               | TESTQA016 | TESTQA016 | English-Canada            |               | 123 STREET | V1Z 1A3    |   5646556564 | test@test.com | No        |               |              |             |                |                  |                  |             |               |     |              |              |            |
      |        3 | Harley_Canada | English-Canada | hdqaauto | 0HD50020 | ******   | 1HD4CR213GC441026 | HARLEY-DAVIDSON | SPORTSTER | SUPERFLOW | 2016 | 2020-12-14    | Alberta [ AB ] | 2020-12-14           | Yes              |                       | New              | CASH        |     1000 | HARLEY-DAVIDSON THEFT PROTECTION    |                 | THEFT PROTECTION |   60 |           |          0 |        175 |              |              |         8.75 |              |             183.75 |          200 |             |             |        8.75 |             |        208.75 |                      |                      | TESTTHEFT001     | No               | TESTQA011 | TESTQA011 | English-Canada            |               | 123 STREET | V1Z 1A3    |   5646556564 | test@test.com | No        |               |              |             |                |                  |                  |       10000 |         15000 | 0.5 |        10000 |        25000 |            |
      |        4 | Harley_Canada | English-Canada | hdqaauto | 0HD50020 | ******   | 1HD4CR213GC441025 | HARLEY-DAVIDSON | SPORTSTER | SUPERFLOW | 2016 | 2020-12-14    | Alberta [ AB ] | 2020-12-14           | Yes              |                       | CPO              | BALLOON     |    60000 | HARLEY-DAVIDSON THEFT PROTECTION    |                 | THEFT PROTECTION |   60 |           |          0 |        175 |              |              |         8.75 |              |             183.75 |          200 |             |             |        8.75 |             |        208.75 |                      |                      | TESTTHEFT002     | No               | TESTQA012 | TESTQA012 | English-Canada            |               | 123 STREET | V1Z 1A3    |   5646556564 | test@test.com | No        |               |              |             |                |                  |                  |       10000 |         15000 | 0.5 |        10000 |        25000 |            |
      |        5 | Harley_Canada | English-Canada | hdqaauto | 0HD50020 | ******   | 1HD2XAEB1LB800995 | HARLEY-DAVIDSON | LIVEWIRE  | BASE      | 2020 | 2020-12-14    | Alberta [ AB ] | 2020-12-14           | Yes              |                       | New              | CASH        |     1000 | HARLEY-DAVIDSON GPS THEFT           |                 | THEFT-GPS        |   60 |           |          0 |        185 |              |              |         9.25 |              |             194.25 |          200 |             |             |          10 |             |           210 |                      |                      | TESTTHEFT003     | No               | TESTQA011 | TESTQA011 | English-Canada            |               | 123 STREET | V1Z 1A3    |   5646556564 | test@test.com | No        |               |              |             |                |                  |                  |       10000 |         15000 | 0.5 |        10000 |        25000 |            |
      |        6 | Harley_Canada | English-Canada | hdqaauto | 0HD50020 | ******   | 1HD2XAEB1LB800989 | HARLEY-DAVIDSON | LIVEWIRE  | BASE      | 2020 | 2020-12-14    | Alberta [ AB ] | 2020-12-14           | Yes              |                       | Pre-Owned        | BALLOON     |     2000 | HARLEY-DAVIDSON GPS THEFT           |                 | THEFT-GPS        |   60 |           |          0 |        185 |              |              |         9.25 |              |             194.25 |          200 |             |             |          10 |             |           210 |                      |                      | TESTTHEFT004     | No               | TESTQA012 | TESTQA012 | English-Canada            |               | 123 STREET | V1Z 1A3    |   5646556564 | test@test.com | No        |               |              |             |                |                  |                  |       10000 |         15000 | 0.5 |        10000 |        25000 |            |
      |        7 | Harley_Canada | English-Canada | hdqaauto | 0HD50020 | ******   | 1HD1GZM18FC313196 | HARLEY-DAVIDSON | SPORTSTER | SUPERFLOW | 2016 | 2020-12-14    | Alberta [ AB ] | 2020-12-14           | Yes              |                       | Pre-Owned        | FINANCE     |    10000 | HARLEY-DAVIDSON GAP PROTECTION      |                 | GAP PROTECTION   |   48 |           |          0 |        299 |              |              |        14.95 |              |             313.95 |          300 |             |             |       14.95 |             |        314.95 |                      |                      |                  | No               | TESTQA013 | TESTQA013 | English-Canada            |               | 123 STREET | V1Z 1A3    |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |       10000 |         15000 | 0.5 |              |              |            |
      |        8 | Harley_Canada | English-Canada | hdqaauto | 0HD50020 | ******   | 1HD1GZM18FC312295 | HARLEY-DAVIDSON | SPORTSTER | SUPERFLOW | 2016 | 2020-12-14    | Alberta [ AB ] | 2020-12-14           | Yes              |                       | New              | FINANCE     |      500 | HARLEY-DAVIDSON GAP PROTECTION      |                 | GAP PROTECTION   |   24 |           |          0 |        299 |              |              |        14.95 |              |             313.95 |          300 |             |             |       14.95 |             |        314.95 |                      |                      |                  | No               | TESTQA014 | TESTQA014 | English-Canada            |               | 123 STREET | V1Z 1A3    |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |       10000 |         15000 | 0.5 |              |              |            |

  @SubmitContract_HD_CA_PROD
  Scenario Outline: Save and Submit the New Contract
    Given Go to url with data as "<TestCase>" and "<Portal>" and "<Language>"and "<Dealer>"
    And Login as "<UserName>" and "<Password>" and "<Captcha>"
    When Click on add New eContract
    And Decode the VIN "<Vin>"
    And Enter contract purchase information "<Vin>" and "<Trim>" and "<Inservicedate>" and "<ContractPurchaseDate>" and "<Vehicle_Purchase>" and "<Vehicle_Purchase_Date>" and "<Vehicle_condtion>" and "<FinanceType>" and "<odometer>" and "<Province>"
    And Select product and get rates "<SelectProduct>" and "<BundleSelection>" and "<Plan>" and "<Term>" and "<TermMiles>" and "<Deductible>" and "<RetailPrice>" and "<DealerCost>" and "<FirstServiceInterval>" and "<FinalServiceInterval>" and "<RegistrationCode>"
    And Verify Dealer Cost and Candian Taxation "<DealerCost>" and "<ExpDealerHST>" and "<ExpDealerGST>" and "<ExpDealerPST>" and "<ExpDealerQST>" and "<ExpDealerCostTotal>"
    And Verify Customer Cost and Candian Taxation "<CustomerCost>" and "<CustomerHST>" and "<CustomerGST>" and "<CustomerPST>" and "<CustomerQST>" and "<ExpTotalCustomerCost>"
    And Enter customer details "<isThisaBussiness>" and "<customerAgreementLanguage>" and "<BussinessName>" and "<FirstName>" and "<LastName>" and "<Address>" and "<PostalCode>" and "<PhoneNumber1>" and "<EmailAddress>" and "<Co-Signer>" and "<cos-First Name>" and "<cos-Last Name>" and "<cos-Address>" and "<cos-Postal Code>" and "<cos-Phone Number 1>" and "<cos-Email Address>" and "<SelectProduct>"
    And Enter vehicle purchase price and finance info "<SelectProduct>" and "<VehicleMSRP>" and "<FinanceAmount>" and  "<APR>" and "<GrossCapCost>" and "<Vehicleprice>"
    And Select Lienholder "<Lienholder>" and "<SelectProduct>"
    And Save the contract
    And Go to the summary page
    And Click on Manage Saved eContracts
    And Select the contract with Last Name "<LastName>", VIN "<Vin>", Product "<SelectProduct>" and Portal "<Portal>"
    And Submit the contract
    Then Logout out from the portal

    Examples: 
      | TestCase | Portal        | Language       | UserName | Dealer   | Password | Vin               | Make            | Model     | Trim      | Year | Inservicedate | Province       | ContractPurchaseDate | Vehicle_Purchase | Vehicle_Purchase_Date | Vehicle_condtion | FinanceType | odometer | SelectProduct                       | BundleSelection | Plan             | Term | TermMiles | Deductible | DealerCost | ExpDealerHST | ExpDealerPST | ExpDealerGST | ExpDealerQST | ExpDealerCostTotal | CustomerCost | CustomerHST | CustomerPST | CustomerGST | CustomerQST | CustTotalCost | FirstServiceInterval | FinalServiceInterval | RegistrationCode | isThisaBussiness | FirstName | LastName  | customerAgreementLanguage | BussinessName | Address    | PostalCode | PhoneNumber1 | EmailAddress  | Co-Signer | cos-FirstName | cos-LastName | cos-Address | cos-PostalCode | cos-PhoneNumber1 | cos-EmailAddress | VehicleMSRP | FinanceAmount | APR | GrossCapCost | Vehicleprice | Lienholder |
      |        1 | Harley_Canada | English-Canada | hdqaauto | 0HD50020 | ******   | 1HD1JRV10FB020636 | HARLEY-DAVIDSON | SPORTSTER | SUPERFLOW | 2016 | 2020-12-14    | Alberta [ AB ] | 2020-12-14           | Yes              |                       | New              | CASH        |     1000 | HARLEY-DAVIDSON PLANNED MAINTENANCE |                 |                  |      |           |          0 |        835 |              |              |        41.75 |              |             876.75 |          800 |             |             |          35 |             |           835 | 24000 KILOMETERS     | 32000 KILOMETERS     |                  | No               | TESTQA015 | TESTQA015 | English-Canada            |               | 123 STREET | V1Z 1A3    |   5646556564 | test@test.com | No        |               |              |             |                |                  |                  |             |               |     |              |              |            |
      |        2 | Harley_Canada | English-Canada | hdqaauto | 0HD50020 | ******   | 5HD2XAEB4LB800116 | HARLEY-DAVIDSON | LIVEWIRE  | BASE      | 2020 | 2020-12-14    | Alberta [ AB ] | 2020-12-14           | Yes              |                       | Pre-Owned        | CASH        |       11 | HARLEY-DAVIDSON PLANNED MAINTENANCE |                 |                  |      |           |          0 |       1469 |              |              |        73.45 |              |            1542.45 |         1500 |             |             |          55 |             |        1555.0 | 48000 KILOMETERS     | 80000 KILOMETERS     |                  | No               | TESTQA016 | TESTQA016 | English-Canada            |               | 123 STREET | V1Z 1A3    |   5646556564 | test@test.com | No        |               |              |             |                |                  |                  |             |               |     |              |              |            |
      |        3 | Harley_Canada | English-Canada | hdqaauto | 0HD50020 | ******   | 1HD4CR213GC441026 | HARLEY-DAVIDSON | SPORTSTER | SUPERFLOW | 2016 | 2020-12-14    | Alberta [ AB ] | 2020-12-14           | Yes              |                       | New              | CASH        |     1000 | HARLEY-DAVIDSON THEFT PROTECTION    |                 | THEFT PROTECTION |   60 |           |          0 |        175 |              |              |         8.75 |              |             183.75 |          200 |             |             |        8.75 |             |        208.75 |                      |                      | TESTTHEFT001     | No               | TESTQA011 | TESTQA011 | English-Canada            |               | 123 STREET | V1Z 1A3    |   5646556564 | test@test.com | No        |               |              |             |                |                  |                  |       10000 |         15000 | 0.5 |        10000 |        25000 |            |
      |        4 | Harley_Canada | English-Canada | hdqaauto | 0HD50020 | ******   | 1HD4CR213GC441026 | HARLEY-DAVIDSON | SPORTSTER | SUPERFLOW | 2016 | 2020-12-14    | Alberta [ AB ] | 2020-12-14           | Yes              |                       | CPO              | BALLOON     |    60000 | HARLEY-DAVIDSON THEFT PROTECTION    |                 | THEFT PROTECTION |   60 |           |          0 |        175 |              |              |         8.75 |              |             183.75 |          200 |             |             |        8.75 |             |        208.75 |                      |                      | TESTTHEFT002     | No               | TESTQA012 | TESTQA012 | English-Canada            |               | 123 STREET | V1Z 1A3    |   5646556564 | test@test.com | No        |               |              |             |                |                  |                  |       10000 |         15000 | 0.5 |        10000 |        25000 |            |
      |        5 | Harley_Canada | English-Canada | hdqaauto | 0HD50020 | ******   | 1HD2XAEB1LB800997 | HARLEY-DAVIDSON | LIVEWIRE  | BASE      | 2020 | 2020-12-14    | Alberta [ AB ] | 2020-12-14           | Yes              |                       | New              | CASH        |     1000 | HARLEY-DAVIDSON GPS THEFT           |                 | THEFT-GPS        |   60 |           |          0 |        185 |              |              |         9.25 |              |             194.25 |          200 |             |             |          10 |             |           210 |                      |                      | TESTTHEFT003     | No               | TESTQA011 | TESTQA011 | English-Canada            |               | 123 STREET | V1Z 1A3    |   5646556564 | test@test.com | No        |               |              |             |                |                  |                  |       10000 |         15000 | 0.5 |        10000 |        25000 |            |
      |        6 | Harley_Canada | English-Canada | hdqaauto | 0HD50020 | ******   | 1HD2XAEB1LB800989 | HARLEY-DAVIDSON | LIVEWIRE  | BASE      | 2020 | 2020-12-14    | Alberta [ AB ] | 2020-12-14           | Yes              |                       | Pre-Owned        | BALLOON     |     2000 | HARLEY-DAVIDSON GPS THEFT           |                 | THEFT-GPS        |   60 |           |          0 |        185 |              |              |         9.25 |              |             194.25 |          200 |             |             |          10 |             |           210 |                      |                      | TESTTHEFT004     | No               | TESTQA012 | TESTQA012 | English-Canada            |               | 123 STREET | V1Z 1A3    |   5646556564 | test@test.com | No        |               |              |             |                |                  |                  |       10000 |         15000 | 0.5 |        10000 |        25000 |            |
      |        7 | Harley_Canada | English-Canada | hdqaauto | 0HD50020 | ******   | 1HD1GZM18FC313196 | HARLEY-DAVIDSON | SPORTSTER | SUPERFLOW | 2016 | 2020-12-14    | Alberta [ AB ] | 2020-12-14           | Yes              |                       | Pre-Owned        | FINANCE     |    10000 | HARLEY-DAVIDSON GAP PROTECTION      |                 | GAP PROTECTION   |   48 |           |          0 |        299 |              |              |        14.95 |              |             313.95 |          300 |             |             |       14.95 |             |        314.95 |                      |                      |                  | No               | TESTQA013 | TESTQA013 | English-Canada            |               | 123 STREET | V1Z 1A3    |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |       10000 |         15000 | 0.5 |              |              |            |
      |        8 | Harley_Canada | English-Canada | hdqaauto | 0HD50020 | ******   | 1HD1GZM18FC312296 | HARLEY-DAVIDSON | SPORTSTER | SUPERFLOW | 2016 | 2020-12-14    | Alberta [ AB ] | 2020-12-14           | Yes              |                       | New              | FINANCE     |      500 | HARLEY-DAVIDSON GAP PROTECTION      |                 | GAP PROTECTION   |   24 |           |          0 |        299 |              |              |        14.95 |              |             313.95 |          300 |             |             |       14.95 |             |        314.95 |                      |                      |                  | No               | TESTQA014 | TESTQA014 | English-Canada            |               | 123 STREET | V1Z 1A3    |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |       10000 |         15000 | 0.5 |              |              |            |
