Feature: To Test HD US Portal Functionalities

  @SaveContract_HD_US_PROD
  Scenario Outline: Add a New Contract
    Given Go to url with data as "<TestCase>" and "<Portal>" and "<Language>"and "<Dealer>"
    And Login as "<UserName>" and "<Password>" and "<Captcha>"
    When Click on add New eContract
    And Decode the VIN "<Vin>"
    And Enter contract purchase information "<Vin>" and "<Trim>" and "<Inservicedate>" and "<ContractPurchaseDate>" and "<Vehicle_Purchase>" and "<Vehicle_Purchase_Date>" and "<Vehicle_condtion>" and "<FinanceType>" and "<odometer>" and "<Province>"
    And Select product and get rates "<SelectProduct>" and "<BundleSelection>" and "<Plan>" and "<Term>" and "<TermMiles>" and "<Deductible>" and "<RetailPrice>" and "<DealerCost>" and "<FirstServiceInterval>" and "<FinalServiceInterval>" and "<RegistrationCode>"
    And Verify Dealer Cost and Retail Price "<DealerCost>" and "<RetailPrice>"
    And Enter customer details "<isThisaBussiness>" and "<customerAgreementLanguage>" and "<BussinessName>" and "<FirstName>" and "<LastName>" and "<Address>" and "<PostalCode>" and "<PhoneNumber1>" and "<EmailAddress>" and "<Co-Signer>" and "<cos-First Name>" and "<cos-Last Name>" and "<cos-Address>" and "<cos-Postal Code>" and "<cos-Phone Number 1>" and "<cos-Email Address>" and "<SelectProduct>"
    And Enter vehicle purchase price and finance info "<SelectProduct>" and "<VehicleMSRP>" and "<FinanceAmount>" and  "<APR>" and "<GrossCapCost>" and "<Vehicleprice>"
    And Select Lienholder "<Lienholder>" and "<SelectProduct>"
    And Save the contract
    And Go to the summary page
    Then Logout out from the portal

    Examples: 
      | TestCase | Portal    | Language | Dealer   | UserName | Password | Captcha | Vin               | Make | Model | Trim | Year | Inservicedate | ContractPurchaseDate | Vehicle_Purchase | Vehicle_Purchase_Date | Vehicle_condtion | FinanceType | odometer | SelectProduct                                  | BundleSelection | Plan                 | Term | TermMiles | Deductible | FirstServiceInterval | FinalServiceInterval | RegistrationCode | DealerCost | RetailPrice | isThisaBussiness | BussinessName | FirstName | LastName  | Address    | PostalCode | PhoneNumber1 | EmailAddress  | Co-Signer | cos-FirstName | cos-LastName | cos-Address | cos-PostalCode | cos-PhoneNumber1 | cos-EmailAddress | VehicleMSRP | FinanceAmount | APR | GrossCapCost | Vehicleprice | Lienholder |
      |        1 | Harley_us |          | 00HD0262 | hdqausau | ******** |         | 1HD2XAEB4LB800162 |      |       |      |      |               | 12/14/2020           | Yes              |                       | NEW              | CASH        |     1000 | HARLEY-DAVIDSON PLANNED MAINTENANCE            |                 |                      |      |           |          0 | 1000 MILES           | 5000 MILES           |                  |        418 |         544 | No               |               | TEST011   | TESTQA011 | 123 STREET |      12345 |   5646556564 | test@test.com | No        |               |              |             |                |                  |                  |             |               |     |              |              |            |
      |        2 | Harley_us |          | 00HD0262 | hdqausau | ******** |         | 1HD1LC315GC408868 |      |       |      |      |               | 12/14/2020           | Yes              |                       | Pre-Owned        | CASH        |    15000 | HARLEY-DAVIDSON PLANNED MAINTENANCE            |                 |                      |      |           |          0 | 20000 MILES          | 40000 MILES          |                  |       1388 |        1805 | No               |               | TEST012   | TESTQA012 | 123 STREET |      12345 |   5646556564 | test@test.com | No        |               |              |             |                |                  |                  |             |               |     |              |              |            |
      |        3 | Harley_us |          | 00HD0262 | hdqausau | ******** |         | 1HD4NBB13GC501468 |      |       |      |      |               | 12/14/2020           | Yes              |                       | NEW              | FINANCE     |      800 | HARLEY-DAVIDSON PLANNED MAINTENANCE            |                 |                      |      |           |          0 | 10000 MILES          | 25000 MILES          |                  |       1758 |        2286 | No               |               | TEST013   | TESTQA013 | 123 STREET |      12345 |   5646556564 | test@test.com | No        |               |              |             |                |                  |                  |             |               |     |              |              |            |
      |        4 | Harley_us |          | 00HD0262 | hdqausau | ******** |         | 1HD1LC315GC408868 |      |       |      |      |               | 12/14/2020           | Yes              |                       | Pre-Owned        | CASH        |     5000 | HARLEY-DAVIDSON THEFT PROTECTION               |                 | THEFT PROTECTION     |   60 |           |          0 |                      |                      | TESTTHEFT001     |        190 |         480 | No               |               | TEST014   | TESTQA014 | 123 STREET |      12345 |   5646556564 | test@test.com | No        |               |              |             |                |                  |                  |       10000 |         15000 | 0.5 |        10000 |        25000 |            |
      |        5 | Harley_us |          | 00HD0262 | hdqausau | ******** |         | 1HD1JRV11HB037668 |      |       |      |      |               | 12/14/2020           | Yes              |                       | Pre-Owned        | FINANCE     |     5000 | HARLEY-DAVIDSON THEFT PROTECTION               |                 | THEFT PROTECTION     |   60 |           |          0 |                      |                      | TESTTHEFT002     |        190 |         480 | No               |               | TEST015   | TESTQA015 | 123 STREET |      12345 |   5646556564 | test@test.com | No        |               |              |             |                |                  |                  |       10000 |         15000 | 0.5 |        10000 |        25000 |            |
      |        6 | Harley_us |          | 00HD0262 | hdqausau | ******** |         | 1HD4CR213GC441063 |      |       |      |      |               | 12/14/2020           | Yes              |                       | NEW              | CASH        |     5000 | HARLEY-DAVIDSON THEFT PROTECTION               |                 | THEFT PROTECTION     |   60 |           |          0 |                      |                      | TESTTHEFT003     |        190 |         480 | No               |               | TEST016   | TESTQA016 | 123 STREET |      12345 |   5646556564 | test@test.com | No        |               |              |             |                |                  |                  |       10000 |         15000 | 0.5 |        10000 |        25000 |            |
      |        7 | Harley_us |          | 00HD0262 | hdqausau | ******** |         | 1HD2XAEB4LB800603 |      |       |      |      |               | 12/14/2020           | Yes              |                       | NEW              | BALLOON     |      800 | HARLEY-DAVIDSON GPS THEFT PROTECTION           |                 | GPS THEFT PROTECTION |   60 |           |          0 |                      |                      | TESTTHEFT004     |        210 |         500 | No               |               | TEST017   | TESTQA017 | 123 STREET |      12345 |   5646556564 | test@test.com | No        |               |              |             |                |                  |                  |       10000 |         15000 | 0.5 |        10000 |        25000 |            |
      |        8 | Harley_us |          | 00HD0262 | hdqausau | ******** |         | 1HD2XAEB4LB800611 |      |       |      |      |               | 12/14/2020           | Yes              |                       | NEW              | FINANCE     |      500 | HARLEY-DAVIDSON GPS THEFT PROTECTION           |                 | GPS THEFT PROTECTION |   60 |           |          0 |                      |                      | TESTTHEFT005     |        210 |         500 | No               |               | TEST018   | TESTQA018 | 123 STREET |      12345 |   5646556564 | test@test.com | No        |               |              |             |                |                  |                  |       10000 |         15000 | 0.5 |        10000 |        25000 |            |
      |        9 | Harley_us |          | 00HD0262 | hdqausau | ******** |         | 1HD2XAEB4LB800171 |      |       |      |      |               | 12/14/2020           | Yes              |                       | Pre-Owned        | CASH        |     5000 | HARLEY-DAVIDSON GPS THEFT PROTECTION           |                 | GPS THEFT PROTECTION |   60 |           |          0 |                      |                      | TESTTHEFT006     |        210 |         500 | No               |               | TEST019   | TESTQA019 | 123 STREET |      12345 |   5646556564 | test@test.com | No        |               |              |             |                |                  |                  |       10000 |         15000 | 0.5 |        10000 |        25000 |            |
      |       10 | Harley_us |          | 00HD3301 | 00HD3301 | ******** |         | 1HD1YHK14LB064078 |      |       |      |      |               | 12/14/2020           | Yes              |                       | NEW              | FINANCE     |      800 | HD PREPAID MAINTENANCE OVERSEAS MILITARY SALES |                 |                      |      |           |          0 | 1000 MILES           | 1000 MILES           |                  |        412 |         500 | No               |               | TEST020   | TESTQA020 | 123 STREET |      12345 |   5646556564 | test@test.com | No        |               |              |             |                |                  |                  |             |               |     |              |              |            |
      |       11 | Harley_us |          | 00HD3301 | 00HD3301 | ******** |         | 1HD1YHK14LB064659 |      |       |      |      |               | 12/14/2020           | Yes              |                       | NEW              | FINANCE     |      800 | HD PREPAID MAINTENANCE OVERSEAS MILITARY SALES |                 |                      |      |           |          0 | 1000 MILES           | 5000 MILES           |                  |        731 |         367 | No               |               | TEST021   | TESTQA021 | 123 STREET |      12345 |   5646556564 | test@test.com | No        |               |              |             |                |                  |                  |             |               |     |              |              |            |
      |       12 | Harley_us |          | 00HD3301 | 00HD3301 | ******** |         | 1HD1YHK14LB064750 |      |       |      |      |               | 12/14/2020           | Yes              |                       | NEW              | CASH        |      800 | HD PREPAID MAINTENANCE OVERSEAS MILITARY SALES |                 |                      |      |           |          0 | 1000 MILES           | 10000 MILES          |                  |       1133 |         829 | No               |               | TEST022   | TESTQA022 | 123 STREET |      12345 |   5646556564 | test@test.com | No        |               |              |             |                |                  |                  |             |               |     |              |              |            |

  @SubmitContract_HD_US_PROD
  Scenario Outline: Save and Submit the New Contract
    Given Go to url with data as "<TestCase>" and "<Portal>" and "<Language>"and "<Dealer>"
    And Login as "<UserName>" and "<Password>" and "<Captcha>"
    When Click on add New eContract
    And Decode the VIN "<Vin>"
    And Enter contract purchase information "<Vin>" and "<Trim>" and "<Inservicedate>" and "<ContractPurchaseDate>" and "<Vehicle_Purchase>" and "<Vehicle_Purchase_Date>" and "<Vehicle_condtion>" and "<FinanceType>" and "<odometer>" and "<Province>"
    And Select product and get rates "<SelectProduct>" and "<BundleSelection>" and "<Plan>" and "<Term>" and "<TermMiles>" and "<Deductible>" and "<RetailPrice>" and "<DealerCost>" and "<FirstServiceInterval>" and "<FinalServiceInterval>" and "<RegistrationCode>"
    And Verify Dealer Cost and Retail Price "<DealerCost>" and "<RetailPrice>"
    And Enter customer details "<isThisaBussiness>" and "<customerAgreementLanguage>" and "<BussinessName>" and "<FirstName>" and "<LastName>" and "<Address>" and "<PostalCode>" and "<PhoneNumber1>" and "<EmailAddress>" and "<Co-Signer>" and "<cos-First Name>" and "<cos-Last Name>" and "<cos-Address>" and "<cos-Postal Code>" and "<cos-Phone Number 1>" and "<cos-Email Address>" and "<SelectProduct>"
    And Enter vehicle purchase price and finance info "<SelectProduct>" and "<VehicleMSRP>" and "<FinanceAmount>" and  "<APR>" and "<GrossCapCost>" and "<Vehicleprice>"
    And Select Lienholder "<Lienholder>" and "<SelectProduct>"
    And Save the contract
    And Go to the summary page
    And Click on Manage Saved eContracts
    And Select the contract with Last Name "<LastName>", VIN "<Vin>", Product "<SelectProduct>" and Portal "<Portal>"
    And Submit the contract
    Then Logout out from the portal

    Examples: 
      | TestCase | Portal    | Language | Dealer   | UserName | Password | Captcha | Vin               | Make | Model | Trim | Year | Inservicedate | ContractPurchaseDate | Vehicle_Purchase | Vehicle_Purchase_Date | Vehicle_condtion | FinanceType | odometer | SelectProduct                        | BundleSelection | Plan                 | Term | TermMiles | Deductible | FirstServiceInterval | FinalServiceInterval | RegistrationCode | DealerCost | RetailPrice | isThisaBussiness | BussinessName | FirstName | LastName  | Address    | PostalCode | PhoneNumber1 | EmailAddress  | Co-Signer | cos-FirstName | cos-LastName | cos-Address | cos-PostalCode | cos-PhoneNumber1 | cos-EmailAddress | VehicleMSRP | FinanceAmount | APR | GrossCapCost | Vehicleprice | Lienholder |
      |        1 | Harley_us |          | 00HD0262 | hdqausau | ******** |         | 1HD2XAEB4LB800191 |      |       |      |      |               | 12/14/2020           | Yes              |                       | NEW              | CASH        |     1000 | HARLEY-DAVIDSON PLANNED MAINTENANCE  |                 |                      |      |           |          0 | 1000 MILES           | 5000 MILES           |                  |        418 |         544 | No               |               | TEST011   | TESTQA011 | 123 STREET |      12345 |   5646556564 | test@test.com | No        |               |              |             |                |                  |                  |             |               |     |              |              |            |
      |        2 | Harley_us |          | 00HD0262 | hdqausau | ******** |         | 1HD1LC315GC408888 |      |       |      |      |               | 12/14/2020           | Yes              |                       | Pre-Owned        | CASH        |    15000 | HARLEY-DAVIDSON PLANNED MAINTENANCE  |                 |                      |      |           |          0 | 20000 MILES          | 40000 MILES          |                  |       1388 |        1805 | No               |               | TEST012   | TESTQA012 | 123 STREET |      12345 |   5646556564 | test@test.com | No        |               |              |             |                |                  |                  |             |               |     |              |              |            |
      |        3 | Harley_us |          | 00HD0262 | hdqausau | ******** |         | 1HD4NBB13GC501448 |      |       |      |      |               | 12/14/2020           | Yes              |                       | NEW              | FINANCE     |      800 | HARLEY-DAVIDSON PLANNED MAINTENANCE  |                 |                      |      |           |          0 | 10000 MILES          | 25000 MILES          |                  |       1758 |        2286 | No               |               | TEST013   | TESTQA013 | 123 STREET |      12345 |   5646556564 | test@test.com | No        |               |              |             |                |                  |                  |             |               |     |              |              |            |
      |        4 | Harley_us |          | 00HD0262 | hdqausau | ******** |         | 1HD1LC315GC408898 |      |       |      |      |               | 12/14/2020           | Yes              |                       | Pre-Owned        | CASH        |     5000 | HARLEY-DAVIDSON THEFT PROTECTION     |                 | THEFT PROTECTION     |   60 |           |          0 |                      |                      | TESTTHEFT001     |        190 |         480 | No               |               | TEST014   | TESTQA014 | 123 STREET |      12345 |   5646556564 | test@test.com | No        |               |              |             |                |                  |                  |       10000 |         15000 | 0.5 |        10000 |        25000 |            |
      |        5 | Harley_us |          | 00HD0262 | hdqausau | ******** |         | 1HD1JRV11HB037628 |      |       |      |      |               | 12/14/2020           | Yes              |                       | Pre-Owned        | FINANCE     |     5000 | HARLEY-DAVIDSON THEFT PROTECTION     |                 | THEFT PROTECTION     |   60 |           |          0 |                      |                      | TESTTHEFT002     |        190 |         480 | No               |               | TEST015   | TESTQA015 | 123 STREET |      12345 |   5646556564 | test@test.com | No        |               |              |             |                |                  |                  |       10000 |         15000 | 0.5 |        10000 |        25000 |            |
      |        6 | Harley_us |          | 00HD0262 | hdqausau | ******** |         | 1HD4CR213GC441058 |      |       |      |      |               | 12/14/2020           | Yes              |                       | NEW              | CASH        |     5000 | HARLEY-DAVIDSON THEFT PROTECTION     |                 | THEFT PROTECTION     |   60 |           |          0 |                      |                      | TESTTHEFT003     |        190 |         480 | No               |               | TEST016   | TESTQA016 | 123 STREET |      12345 |   5646556564 | test@test.com | No        |               |              |             |                |                  |                  |       10000 |         15000 | 0.5 |        10000 |        25000 |            |
      |        7 | Harley_us |          | 00HD0262 | hdqausau | ******** |         | 1HD2XAEB4LB800101 |      |       |      |      |               | 12/14/2020           | Yes              |                       | NEW              | BALLOON     |      800 | HARLEY-DAVIDSON GPS THEFT PROTECTION |                 | GPS THEFT PROTECTION |   60 |           |          0 |                      |                      | TESTTHEFT004     |        210 |         500 | No               |               | TEST017   | TESTQA017 | 123 STREET |      12345 |   5646556564 | test@test.com | No        |               |              |             |                |                  |                  |       10000 |         15000 | 0.5 |        10000 |        25000 |            |
      |        8 | Harley_us |          | 00HD0262 | hdqausau | ******** |         | 1HD2XAEB4LB800111 |      |       |      |      |               | 12/14/2020           | Yes              |                       | NEW              | FINANCE     |      500 | HARLEY-DAVIDSON GPS THEFT PROTECTION |                 | GPS THEFT PROTECTION |   60 |           |          0 |                      |                      | TESTTHEFT005     |        210 |         500 | No               |               | TEST018   | TESTQA018 | 123 STREET |      12345 |   5646556564 | test@test.com | No        |               |              |             |                |                  |                  |       10000 |         15000 | 0.5 |        10000 |        25000 |            |
      |        9 | Harley_us |          | 00HD0262 | hdqausau | ******** |         | 1HD2XAEB4LB800121 |      |       |      |      |               | 12/14/2020           | Yes              |                       | Pre-Owned        | CASH        |     5000 | HARLEY-DAVIDSON GPS THEFT PROTECTION |                 | GPS THEFT PROTECTION |   60 |           |          0 |                      |                      | TESTTHEFT006     |        210 |         500 | No               |               | TEST019   | TESTQA019 | 123 STREET |      12345 |   5646556564 | test@test.com | No        |               |              |             |                |                  |                  |       10000 |         15000 | 0.5 |        10000 |        25000 |            |
