Feature: To Test PBL CANADA Portal Functionalities

  @SaveContract_PBL_CANADA_PROD
  Scenario Outline: Save Contract
    Given Go to url with data as "<TestCase>" and "<Portal>" and "<Language>"and "<Dealer>"
    And Login as "<UserName>" and "<Password>" and "<Captcha>"
    When Click on add New eContract
    And Decode the VIN "<Vin>"
    And Enter contract purchase information "<Vin>" and "<Trim>" and "<Inservicedate>" and "<ContractPurchaseDate>" and "<Vehicle_Purchase>" and "<Vehicle_Purchase_Date>" and "<Vehicle_condtion>" and "<FinanceType>" and "<odometer>" and "<Province>"
    And Select product and get rates "<SelectProduct>" and "<BundleSelection>" and "<Plan>" and "<Term>" and "<TermMiles>" and "<Deductible>" and "<RetailPrice>" and "<DealerCost>" and "<FirstServiceInterval>" and "<FinalServiceInterval>" and "<RegistrationCode>"
    And Verify Dealer Cost and Candian Taxation "<DealerCost>" and "<ExpDealerHST>" and "<ExpDealerGST>" and "<ExpDealerPST>" and "<ExpDealerQST>" and "<ExpDealerCostTotal>"
    And Verify Customer Cost and Candian Taxation "<CustomerCost>" and "<CustomerHST>" and "<CustomerGST>" and "<CustomerPST>" and "<CustomerQST>" and "<ExpTotalCustomerCost>"
    And Enter customer details "<isThisaBussiness>" and "<customerAgreementLanguage>" and "<BussinessName>" and "<FirstName>" and "<LastName>" and "<Address>" and "<PostalCode>" and "<PhoneNumber1>" and "<EmailAddress>" and "<Co-Signer>" and "<cos-First Name>" and "<cos-Last Name>" and "<cos-Address>" and "<cos-Postal Code>" and "<cos-Phone Number 1>" and "<cos-Email Address>" and "<SelectProduct>"
    And Enter vehicle purchase price and finance info "<SelectProduct>" and "<VehicleMSRP>" and "<FinanceAmount>" and  "<APR>" and "<GrossCapCost>" and "<Vehicleprice>"
    And Select Lienholder "<Lienholder>" and "<SelectProduct>"
    And Save the contract
    And Go to the summary page
    Then Logout out from the portal

    Examples: 
      | TestCase | Portal             | Language       | UserName | Dealer   | Password | Vin               | Make        | Model        | Trim    | Year | Inservicedate | Province       | ContractPurchaseDate | Vehicle_Purchase | Vehicle_Purchase_Date | Vehicle_condtion | FinanceType | odometer | SelectProduct                | BundleSelection | Plan                                                           | Term | TermMiles | Deductible | DealerCost | ExpDealerHST | ExpDealerPST | ExpDealerGST | ExpDealerQST | ExpDealerCostTotal | CustomerCost | CustomerHST | CustomerPST | CustomerGST | CustomerQST | CustTotalCost | FirstServiceInterval                               | FinalServiceInterval                               | RegistrationCode | isThisaBussiness | FirstName | LastName  | customerAgreementLanguage | BussinessName | Address    | PostalCode | PhoneNumber1 | EmailAddress  | Co-Signer | cos-FirstName | cos-LastName | cos-Address | cos-PostalCode | cos-PhoneNumber1 | cos-EmailAddress | VehicleMSRP | FinanceAmount | APR | GrossCapCost | Vehicleprice | Lienholder |
      |        1 | Porsche_Canada     | English-Canada | pcqaauto | PORS2229 | ******   | WP0CA2A80HS221624 | PORSCHE     | 718 BOXSTER  | BASE    | 2017 | 10-08-2020    | Ontario [ ON ] | 10-08-2020           | Yes              | 11/28/2019            | Pre-Owned        | FINANCE     |    18688 | PFS GAP PROTECTION           |                 | Porsche Protection Plan Guaranteed Auto Protection             |   12 | NA        |          0 |        275 |        35.75 |              |              |              |             310.75 |          750 |       97.50 |             |             |             |               |                                                    |                                                    |                  | No               | TESTQA001 | TESTQA001 | French-Canada             |               | 123 STREET | K1A 0A1    |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |       20000 |         15000 | 0.5 |        10000 |        25000 |            |
      |        2 | Porsche_Canada     | English-Canada | pcqaauto | PORS2229 | ******   | WP0CA2A80HS222634 | PORSCHE     | 718 BOXSTER  | BASE    | 2017 | 10-08-2020    | Ontario [ ON ] | 10-08-2020           | Yes              | 11/28/2019            | Pre-Owned        | FINANCE     |     2000 | QUALITYSHIELD GAP PROTECTION |                 | QualityShield Protection Plan Guaranteed Auto Protection (GAP) |   60 | NA        |          0 |        255 |        33.15 |              |              |              |             288.15 |          730 |       94.90 |             |             |             |               |                                                    |                                                    |                  | No               | TESTQA002 | TESTQA002 | French-Canada             |               | 123 STREET | K1A 0A1    |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |       20000 |         15000 | 0.5 |        10000 |        25000 |            |
      |        3 | Porsche_Canada     | English-Canada | pcqaauto | PORS2229 | ******   | WP0AA2A81HS273214 | PORSCHE     | 718 CAYMAN   | BASE    | 2017 | 10-08-2020    | Ontario [ ON ] | 10-08-2020           | Yes              | 11/28/2019            | New              | CASH        |    14999 | PFS MULTI-COVERAGE           | Platinum        | NA                                                             |   12 | NA        |          0 |       1900 |       247.00 |              |              |              |            2147.00 |         3600 |      468.00 |             |             |             |               |                                                    |                                                    |                  | No               | TESTQA003 | TESTQA003 | French-Canada             |               | 123 STREET | K1A 0A1    |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |       20000 |         15000 | 0.5 |        10000 |        25000 |            |
      |        5 | Porsche_Canada     | English-Canada | pcqaauto | PORS2229 | ******   | WP0AF2A98KS165324 | PORSCHE     |          911 | GT3 RS  | 2019 | 10-08-2020    | Ontario [ ON ] | 10-08-2020           | Yes              | 11/28/2019            | New              | LEASE       |       11 | PFS LEASE-END PROTECTION     |                 | Porsche Protection Plan Lease-End Protection                   |   60 | NA        |          0 |       1260 |       163.80 |              |              |              |            1423.80 |         2470 |      321.10 |             |             |             |               |                                                    |                                                    |                  | No               | TESTQA005 | TESTQA005 | French-Canada             |               | 123 STREET | K1A 0A1    |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |       20000 |         15000 | 0.5 |        10000 |        25000 |            |
      |        6 | Bentley_Canada     | English-Canada | bcqaauto | BENT4013 | ******   | SJAAC4ZV1JC018334 | BENTLEY     | BENTAYGA W12 | BASE    | 2017 | 10-08-2020    | Ontario [ ON ] | 10-08-2020           | Yes              | 11/28/2019            | Pre-Owned        | FINANCE     |    18688 | BFS GAP PROTECTION           |                 | Bentley Protection Plan Guaranteed Auto Protection             |   84 | NA        |          0 |       1100 |       143.00 |              |              |              |            1265.00 |         1300 |      165.00 |             |             |             |               |                                                    |                                                    |                  | No               | TESTQA006 | TESTQA006 | French-Canada             |               | 123 STREET | K1A 0A1    |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |       20000 |         15000 | 0.5 |        10000 |        25000 |            |
      |        7 | Bentley_Canada     | English-Canada | bcqaauto | BENT4013 | ******   | SJAAC2ZV2HC015134 | BENTLEY     | BENTAYGA W12 | BASE    | 2017 | 10-08-2020    | Ontario [ ON ] | 10-08-2020           | Yes              | 11/28/2019            | New              | LEASE       |       11 | BFS LEASE-END PROTECTION     |                 | Bentley Protection Plan Lease-End Protection                   |   36 | NA        |          0 |       1815 |       235.95 |              |              |              |            1886.00 |         2000 |      246.00 |             |             |             |               |                                                    |                                                    |                  | No               | TESTQA007 | TESTQA007 | French-Canada             |               | 123 STREET | K1A 0A1    |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |       20000 |         15000 | 0.5 |        10000 |        25000 |            |
      |        8 | Bentley_Canada     | English-Canada | bcqaauto | BENT4013 | ******   | SJAAC2ZV2HC015174 | BENTLEY     | BENTAYGA W12 | BASE    | 2017 | 10-08-2020    | Ontario [ ON ] | 10-08-2020           | Yes              | 11/28/2019            | CPO              | BALLOON     |      594 | BFS PREPAID MAINTENANCE      |                 |                                                                |      |           |          0 |       6362 |       827.06 |              |              |              |            6940.46 |         7682 |      998.66 |             |             |             |               | SECOND YEAR INTERVAL - 24 MONTHS OR 32,000 KILOMET | FOURTH YEAR INTERVAL - 48 MONTHS OR 64,000 KILOMET |                  | No               | TESTQA008 | TESTQA008 | French-Canada             |               | 123 STREET | K1A 0A1    |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |       20000 |         15000 | 0.5 |        10000 |        25000 |            |
      |        9 | Bentley_Canada     | English-Canada | bcqaauto | BENT4013 | ******   | SJAAC4ZV1JC018424 | BENTLEY     | BENTAYGA W12 | BASE    | 2017 | 10-08-2020    | Ontario [ ON ] | 10-08-2020           | Yes              | 11/28/2019            | New              | CASH        |    14999 | BFS MULTI-COVERAGE           | Platinum        |                                                                |   72 | NA        |        100 |       4260 |       553.80 |              |              |              |            4813.80 |         8520 |     1107.60 |             |             |             |       9627.60 |                                                    |                                                    |                  | No               | TESTQA009 | TESTQA009 | French-Canada             |               | 123 STREET | K1A 0A1    |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |       20000 |         15000 | 0.5 |        10000 |        25000 |            |
      |       10 | Lamborghini_Canada | English-Canada | lcqaauto | LAMB6703 | ******   | ZHWUC1ZD4HLA05834 | LAMBORGHINI | AVENTADOR    | LP700_4 | 2017 | 10-08-2020    | Ontario [ ON ] | 10-08-2020           | Yes              | 11/28/2019            | Pre-Owned        | FINANCE     |    18688 | LFS GAP PROTECTION           |                 | Guaranteed Auto Protection                                     |   12 | NA        |          0 |        690 |        89.70 |              |              |              |             793.50 |          800 |      103.50 |             |             |             |               |                                                    |                                                    |                  | No               | TESTQA010 | TESTQA010 | French-Canada             |               | 123 STREET | K1A 0A1    |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |       20000 |         15000 | 0.5 |        10000 |        25000 |            |
      |       11 | Lamborghini_Canada | English-Canada | lcqaauto | LAMB6703 | ******   | ZHWUC1ZD4HLA05864 | LAMBORGHINI | AVENTADOR    | LP700_4 | 2017 | 10-08-2020    | Ontario [ ON ] | 10-08-2020           | Yes              | 11/28/2019            | New              | CASH        |    14999 | LFS MULTI-COVERAGE           | X               |                                                                |   72 | NA        |          0 |       1470 |       191.10 |              |              |              |            1661.10 |         2940 |      382.20 |             |             |             |       3322.20 |                                                    |                                                    |                  | No               | TESTQA011 | TESTQA011 | French-Canada             |               | 123 STREET | K1A 0A1    |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |       20000 |         15000 | 0.5 |        10000 |        25000 |            |
      |       12 | Lamborghini_Canada | English-Canada | lcqaauto | LAMB6703 | ******   | ZHWUC1ZD4HLA05809 | LAMBORGHINI | AVENTADOR    | LP700_4 | 2017 | 10-08-2020    | Ontario [ ON ] | 10-08-2020           | Yes              | 11/28/2019            | New              | LEASE       |       11 | LFS LEASE-END PROTECTION     |                 | Lease-End Protection                                           |   36 | NA        |          0 |       2720 |       353.60 |              |              |              |            2840.50 |         3100 |      370.50 |             |             |             |               |                                                    |                                                    |                  | No               | TESTQA012 | TESTQA012 | French-Canada             |               | 123 STREET | K1A 0A1    |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |       20000 |         15000 | 0.5 |        10000 |        25000 |            |
      |       13 | Lamborghini_Canada | English-Canada | lcqaauto | LAMB6703 | ******   | ZHWUC1ZD4HLA05859 | LAMBORGHINI | AVENTADOR    | LP700_4 | 2017 | 10-08-2020    | Ontario [ ON ] | 10-08-2020           | Yes              | 11/28/2019            | CPO              | BALLOON     |      594 | LFS PREPAID MAINTENANCE      |                 |                                                                |      |           |          0 |     1122.5 |       145.93 |              |              |              |            1290.88 |         1300 |      168.38 |             |             |             |               | 2500 KILOMETERS                                    | 2500 KILOMETERS                                    |                  | No               | TESTQA013 | TESTQA013 | French-Canada             |               | 123 STREET | K1A 0A1    |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |       20000 |         15000 | 0.5 |        10000 |        25000 |            |

  @SubmitContract_PBL_CANADA_PROD
  Scenario Outline: Save and Submit the New Contract
    Given Go to url with data as "<TestCase>" and "<Portal>" and "<Language>"and "<Dealer>"
    And Login as "<UserName>" and "<Password>" and "<Captcha>"
    When Click on add New eContract
    And Decode the VIN "<Vin>"
    And Enter contract purchase information "<Vin>" and "<Trim>" and "<Inservicedate>" and "<ContractPurchaseDate>" and "<Vehicle_Purchase>" and "<Vehicle_Purchase_Date>" and "<Vehicle_condtion>" and "<FinanceType>" and "<odometer>" and "<Province>"
    And Select product and get rates "<SelectProduct>" and "<BundleSelection>" and "<Plan>" and "<Term>" and "<TermMiles>" and "<Deductible>" and "<RetailPrice>" and "<DealerCost>" and "<FirstServiceInterval>" and "<FinalServiceInterval>" and "<RegistrationCode>"
    And Verify Dealer Cost and Candian Taxation "<DealerCost>" and "<ExpDealerHST>" and "<ExpDealerGST>" and "<ExpDealerPST>" and "<ExpDealerQST>" and "<ExpDealerCostTotal>"
    And Verify Customer Cost and Candian Taxation "<CustomerCost>" and "<CustomerHST>" and "<CustomerGST>" and "<CustomerPST>" and "<CustomerQST>" and "<ExpTotalCustomerCost>"
    And Enter customer details "<isThisaBussiness>" and "<customerAgreementLanguage>" and "<BussinessName>" and "<FirstName>" and "<LastName>" and "<Address>" and "<PostalCode>" and "<PhoneNumber1>" and "<EmailAddress>" and "<Co-Signer>" and "<cos-First Name>" and "<cos-Last Name>" and "<cos-Address>" and "<cos-Postal Code>" and "<cos-Phone Number 1>" and "<cos-Email Address>" and "<SelectProduct>"
    And Enter vehicle purchase price and finance info "<SelectProduct>" and "<VehicleMSRP>" and "<FinanceAmount>" and  "<APR>" and "<GrossCapCost>" and "<Vehicleprice>"
    And Select Lienholder "<Lienholder>" and "<SelectProduct>"
    And Save the contract
    And Go to the summary page
    And Click on Manage Saved eContracts
    And Select the contract with Last Name "<LastName>", VIN "<Vin>", Product "<SelectProduct>" and Portal "<Portal>"
    And Submit the contract
    Then Logout out from the portal

    Examples: 
      | TestCase | Portal             | Language       | UserName | Dealer   | Password | Vin               | Make        | Model        | Trim    | Year | Inservicedate | Province       | ContractPurchaseDate | Vehicle_Purchase | Vehicle_Purchase_Date | Vehicle_condtion | FinanceType | odometer | SelectProduct                | BundleSelection | Plan                                                           | Term | TermMiles | Deductible | DealerCost | ExpDealerHST | ExpDealerPST | ExpDealerGST | ExpDealerQST | ExpDealerCostTotal | CustomerCost | CustomerHST | CustomerPST | CustomerGST | CustomerQST | CustTotalCost | FirstServiceInterval                               | FinalServiceInterval                               | RegistrationCode | isThisaBussiness | FirstName | LastName  | customerAgreementLanguage | BussinessName | Address    | PostalCode | PhoneNumber1 | EmailAddress  | Co-Signer | cos-FirstName | cos-LastName | cos-Address | cos-PostalCode | cos-PhoneNumber1 | cos-EmailAddress | VehicleMSRP | FinanceAmount | APR | GrossCapCost | Vehicleprice | Lienholder |
      |        1 | Porsche_Canada     | English-Canada | pcqaauto | PORS2229 | ******   | WP0CA2A80HS220877 | PORSCHE     | 718 BOXSTER  | BASE    | 2017 | 10-08-2020    | Ontario [ ON ] | 12-12-2019           | Yes              | 11/28/2018            | Pre-Owned        | FINANCE     |    18688 | PFS GAP PROTECTION           |                 | Porsche Protection Plan Guaranteed Auto Protection             |   12 | NA        |          0 |        250 |        32.50 |              |              |              |             282.50 |          290 |       35.50 |             |             |             |               |                                                    |                                                    |                  | No               | TESTQA001 | TESTQA001 | French-Canada             |               | 123 STREET | K1A 0A1    |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |       20000 |         15000 | 0.5 |        10000 |        25000 |            |
      |        2 | Porsche_Canada     | English-Canada | pcqaauto | PORS2229 | ******   | WP0AD2A93HS166563 | PORSCHE     |          911 | TURBO S | 2017 | 10-08-2020    | Ontario [ ON ] | 12-12-2019           | Yes              | 11/28/2018            | New              | LEASE       |       11 | PFS LEASE-END PROTECTION     |                 | Porsche Protection Plan Lease-End Protection                   |   36 | NA        |          0 |        960 |       124.80 |              |              |              |            1084.80 |         1000 |         150 |             |             |             |               |                                                    |                                                    |                  | No               | TESTQA002 | TESTQA002 | French-Canada             |               | 123 STREET | K1A 0A1    |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |       20000 |         15000 | 0.5 |        10000 |        25000 |            |
      |        3 | Porsche_Canada     | English-Canada | pcqaauto | PORS2229 | ******   | WP0CA2A80HS220877 | PORSCHE     | 718 BOXSTER  | BASE    | 2017 | 10-08-2020    | Ontario [ ON ] | 12-12-2019           | Yes              | 11/28/2018            | Pre-Owned        | FINANCE     |     2000 | QUALITYSHIELD GAP PROTECTION |                 | QualityShield Protection Plan Guaranteed Auto Protection (GAP) |   60 | NA        |          0 |        230 |        29.90 |              |              |              |             259.90 |          290 |       35.20 |             |             |             |               |                                                    |                                                    |                  | No               | TESTQA003 | TESTQA003 | French-Canada             |               | 123 STREET | K1A 0A1    |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |       20000 |         15000 | 0.5 |        10000 |        25000 |            |
      |        4 | Porsche_Canada     | English-Canada | pcqaauto | PORS2229 | ******   | WP0AA2A81HS270419 | PORSCHE     | 718 CAYMAN   | BASE    | 2017 | 10-08-2020    | Ontario [ ON ] | 12-12-2019           | Yes              | 11/28/2018            | New              | CASH        |    14999 | PFS MULTI-COVERAGE           | Silver          | NA                                                             |   12 | NA        |         50 |       1090 |       141.70 |              |              |              |            1231.70 |         1650 |         300 |             |             |             |               |                                                    |                                                    |                  | No               | TESTQA004 | TESTQA004 | French-Canada             |               | 123 STREET | K1A 0A1    |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |       20000 |         15000 | 0.5 |        10000 |        25000 |            |
      |        5 | Bentley_Canada     | English-Canada | bcqaauto | BENT4013 | ******   | SJAAC4ZV1JC018462 | BENTLEY     | BENTAYGA W12 | BASE    | 2017 | 10-08-2020    | Ontario [ ON ] | 12-12-2019           | Yes              | 11/28/2018            | Pre-Owned        | FINANCE     |    18688 | BFS GAP PROTECTION           |                 | Bentley Protection Plan Guaranteed Auto Protection             |   84 | NA        |          0 |       1100 |       143.00 |              |              |              |            1265.00 |         1300 |      165.00 |             |             |             |               |                                                    |                                                    |                  | No               | TESTQA005 | TESTQA005 | French-Canada             |               | 123 STREET | K1A 0A1    |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |       20000 |         15000 | 0.5 |        10000 |        25000 |            |
      |        6 | Bentley_Canada     | English-Canada | bcqaauto | BENT4013 | ******   | SJAAC2ZV2HC015116 | BENTLEY     | BENTAYGA W12 | BASE    | 2017 | 10-08-2020    | Ontario [ ON ] | 12-12-2019           | Yes              | 11/28/2018            | New              | LEASE       |       11 | BFS LEASE-END PROTECTION     |                 | Bentley Protection Plan Lease-End Protection                   |   36 | NA        |          0 |       1640 |       213.20 |              |              |              |            1886.00 |         2000 |      246.00 |             |             |             |               |                                                    |                                                    |                  | No               | TESTQA006 | TESTQA006 | French-Canada             |               | 123 STREET | K1A 0A1    |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |       20000 |         15000 | 0.5 |        10000 |        25000 |            |
      |        7 | Bentley_Canada     | English-Canada | bcqaauto | BENT4013 | ******   | SJAAC2ZV2HC015116 | BENTLEY     | BENTAYGA W12 | BASE    | 2017 | 10-08-2020    | Ontario [ ON ] | 12-12-2019           | Yes              | 11/28/2018            | CPO              | BALLOON     |      594 | BFS PREPAID MAINTENANCE      | NA              |                                                                |      |           |          0 |       6142 |       798.46 |              |              |              |            6940.46 |         7682 |      998.66 |             |             |             |               | SECOND YEAR INTERVAL - 24 MONTHS OR 32,000 KILOMET | FOURTH YEAR INTERVAL - 48 MONTHS OR 64,000 KILOMET |                  | No               | TESTQA007 | TESTQA007 | French-Canada             |               | 123 STREET | K1A 0A1    |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |       20000 |         15000 | 0.5 |        10000 |        25000 |            |
      |        8 | Bentley_Canada     | English-Canada | bcqaauto | BENT4013 | ******   | SJAAC4ZV1JC018462 | BENTLEY     | BENTAYGA W12 | BASE    | 2017 | 10-08-2020    | Ontario [ ON ] | 12-12-2019           | Yes              | 11/28/2018            | New              | CASH        |    14999 | BFS MULTI-COVERAGE           | Platinum        |                                                                |   72 | NA        |        100 |       4260 |       553.80 |              |              |              |            4813.80 |         8520 |     1107.60 |             |             |             |       9627.60 |                                                    |                                                    |                  | No               | TESTQA008 | TESTQA008 | French-Canada             |               | 123 STREET | K1A 0A1    |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |       20000 |         15000 | 0.5 |        10000 |        25000 |            |
      |        9 | Lamborghini_Canada | English-Canada | lcqaauto | LAMB6703 | ******   | ZHWUC1ZD4HLA05825 | LAMBORGHINI | AVENTADOR    | LP700_4 | 2017 | 10-08-2020    | Ontario [ ON ] | 12-12-2019           | Yes              | 11/28/2018            | Pre-Owned        | FINANCE     |    18688 | LFS GAP PROTECTION           |                 | Lamborghini Protection Plan Guaranteed Auto Protection         |   12 | NA        |          0 |        690 |        89.70 |              |              |              |             793.50 |          800 |      103.50 |             |             |             |               |                                                    |                                                    |                  | No               | TESTQA009 | TESTQA009 | French-Canada             |               | 123 STREET | K1A 0A1    |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |       20000 |         15000 | 0.5 |        10000 |        25000 |            |
      |       10 | Lamborghini_Canada | English-Canada | lcqaauto | LAMB6703 | ******   | ZHWUC1ZD4HLA05825 | LAMBORGHINI | AVENTADOR    | LP700_4 | 2017 | 10-08-2020    | Ontario [ ON ] | 12-12-2019           | Yes              | 11/28/2018            | New              | CASH        |    14999 | LFS MULTI-COVERAGE           | X               |                                                                |   72 | NA        |          0 |       1470 |       191.10 |              |              |              |            1661.10 |         2940 |      382.20 |             |             |             |       3322.20 |                                                    |                                                    |                  | No               | TESTQA010 | TESTQA010 | French-Canada             |               | 123 STREET | K1A 0A1    |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |       20000 |         15000 | 0.5 |        10000 |        25000 |            |
      |       11 | Lamborghini_Canada | English-Canada | lcqaauto | LAMB6703 | ******   | ZHWUC1ZD4HLA05825 | LAMBORGHINI | AVENTADOR    | LP700_4 | 2017 | 10-08-2020    | Ontario [ ON ] | 12-12-2019           | Yes              | 11/28/2018            | New              | LEASE       |       11 | LFS LEASE-END PROTECTION     |                 | Lamborghini Protection Plan Lease-End Protection               |   36 | NA        |          0 |       2470 |       321.10 |              |              |              |            2840.50 |         3100 |      370.50 |             |             |             |               |                                                    |                                                    |                  | No               | TESTQA011 | TESTQA011 | French-Canada             |               | 123 STREET | K1A 0A1    |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |       20000 |         15000 | 0.5 |        10000 |        25000 |            |
      |       12 | Lamborghini_Canada | English-Canada | lcqaauto | LAMB6703 | ******   | ZHWUC1ZD4HLA05825 | LAMBORGHINI | AVENTADOR    | LP700_4 | 2017 | 10-08-2020    | Ontario [ ON ] | 12-12-2019           | Yes              | 11/28/2018            | CPO              | BALLOON     |      594 | LFS PREPAID MAINTENANCE      | NA              |                                                                |      |           |          0 |     1122.5 |       145.93 |              |              |              |            1290.88 |         1300 |      168.38 |             |             |             |               | 2500 KILOMETERS                                    | 2500 KILOMETERS                                    |                  | No               | TESTQA012 | TESTQA012 | French-Canada             |               | 123 STREET | K1A 0A1    |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |       20000 |         15000 | 0.5 |        10000 |        25000 |            |
