Feature: To Test Vroom Portal Functionalities

  @SaveContract_Vroom_PROD
  Scenario Outline: Add a New Contract
    Given Go to url with data as "<TestCase>" and "<Portal>" and "<Language>"and "<Dealer>"
    And Login as "<UserName>" and "<Password>" and "<Captcha>"
    When Click on add New eContract
    And Decode the VIN "<Vin>"
    And Enter contract purchase information "<Vin>" and "<Trim>" and "<Inservicedate>" and "<ContractPurchaseDate>" and "<Vehicle_Purchase>" and "<Vehicle_Purchase_Date>" and "<Vehicle_condtion>" and "<FinanceType>" and "<odometer>" and "<Province>"
    And Select product and get rates "<SelectProduct>" and "<BundleSelection>" and "<Plan>" and "<Term>" and "<TermMiles>" and "<Deductible>" and "<RetailPrice>" and "<DealerCost>" and "<FirstServiceInterval>" and "<FinalServiceInterval>" and "<RegistrationCode>"
    And Verify Dealer Cost and Retail Price "<DealerCost>" and "<RetailPrice>"
    And Enter customer details "<isThisaBussiness>" and "<customerAgreementLanguage>" and "<BussinessName>" and "<FirstName>" and "<LastName>" and "<Address>" and "<PostalCode>" and "<PhoneNumber1>" and "<EmailAddress>" and "<Co-Signer>" and "<cos-First Name>" and "<cos-Last Name>" and "<cos-Address>" and "<cos-Postal Code>" and "<cos-Phone Number 1>" and "<cos-Email Address>" and "<SelectProduct>"
    And Enter vehicle purchase price and finance info "<SelectProduct>" and "<VehicleMSRP>" and "<FinanceAmount>" and  "<APR>" and "<GrossCapCost>" and "<Vehicleprice>"
    And Select Lienholder "<Lienholder>" and "<SelectProduct>"
    And Save the contract
    And Go to the summary page
    Then Logout out from the portal

    Examples: 
      | TestCase | Portal | Language | Dealer   | UserName | Password | Captcha | Vin               | Make | Model | Trim | Year | Inservicedate | ContractPurchaseDate | Vehicle_Purchase | Vehicle_Purchase_Date | Vehicle_condtion | FinanceType | odometer | SelectProduct                        | BundleSelection | Plan                                 | Term | TermMiles | Deductible | FirstServiceInterval | FinalServiceInterval | RegistrationCode | DealerCost | RetailPrice | isThisaBussiness | BussinessName | FirstName | LastName  | Address    | PostalCode | PhoneNumber1 | EmailAddress  | Co-Signer | cos-FirstName | cos-LastName | cos-Address | cos-PostalCode | cos-PhoneNumber1 | cos-EmailAddress | VehicleMSRP | FinanceAmount | APR | GrossCapCost | Vehicleprice | Lienholder |
      |        1 | Vroom  |          | 00AA1005 | vrqaauto | ******** |         | 3VW447AU2HM031522 |      |       |      | 2016 | 2020-10-08    | 2020-10-08           | Yes              |                       | Pre-Owned        | FINANCE     |     2000 | VROOM VSC PROTECTION                 |                 | PLATINUM COVERAGE                    |   48 |    100000 |        100 |                      |                      |                  |       1028 |        1374 | No               |               | TESTQA001 | TESTQA101 | 123 STREET |      90013 |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |       10000 |         15000 | 0.5 |        10000 |        25000 |            |
      |        2 | Vroom  |          | 00AA1005 | vrqaauto | ******** |         | 3VW167AJ2GM282775 |      |       |      | 2016 | 2020-10-08    | 2020-10-08           | Yes              |                       | Pre-Owned        | FINANCE     |     2000 | VROOM GAP PROTECTION                 |                 | VROOM GAP PROTECTION                 |   84 |           |          0 |                      |                      |                  |        233 |         300 | No               |               | TESTQA002 | TESTQA102 | 123 STREET |      90013 |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |       10000 |         15000 | 0.5 |        10000 |        25000 |            |
      |        3 | Vroom  |          | 00AA1005 | vrqaauto | ******** |         | 3VW167AJ2GM244866 |      |       |      | 2016 | 2020-10-08    | 2020-10-08           | Yes              |                       | Pre-Owned        | FINANCE     |     2000 | VROOM ROADSIDE PROTECTION            |                 | VROOM ROADSIDE PROTECTION            |   12 |           |          0 |                      |                      |                  |         18 |          28 | No               |               | TESTQA003 | TESTQA103 | 123 STREET |      90013 |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |       10000 |         15000 | 0.5 |        10000 |        25000 |            |
      |        4 | Vroom  |          | 00AA1005 | vrqaauto | ******** |         | WBA6D6C53GGF53733 |      |       |      | 2016 | 2020-10-08    | 2020-10-08           | Yes              |                       | Pre-Owned        | FINANCE     |     2000 | VROOM SPECIALTY PARTNER LTD WARRANTY |                 | VROOM SPECIALTY PARTNER LTD WARRANTY |    6 |     10000 |         50 |                      |                      |                  |        175 |         200 | No               |               | TESTQA004 | TESTQA104 | 123 STREET |      90013 |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |       10000 |         15000 | 0.5 |        10000 |        25000 |            |
      |        5 | Vroom  |          | 00AA1005 | vrqaauto | ******** |         | WAU57LFF4G1025712 |      |       |      | 2016 | 2020-10-08    | 2020-10-08           | Yes              |                       | Pre-Owned        | FINANCE     |     2000 | VROOM TIRE AND WHEEL PROTECTION      |                 | VROOM TIRE AND WHEEL PROTECTION      |   12 |           |          0 |                      |                      |                  |        231 |         100 | No               |               | TESTQA005 | TESTQA105 | 123 STREET |      90013 |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |       10000 |         15000 | 0.5 |        10000 |        25000 |            |
      |        6 | Vroom  |          | 00AA1005 | vrqaauto | ******** |         | WVWKP7AU1HW146969 |      |       |      | 2016 | 2020-10-08    | 2020-10-08           | Yes              |                       | Pre-Owned        | FINANCE     |     2000 | VROOM VSC LIMITED WARRANTY           |                 | VROOM VSC LIMITED PROTECTION         |    3 |      6000 |         50 |                      |                      |                  |        100 |         120 | No               |               | TESTQA006 | TESTQA106 | 123 STREET |      90013 |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |       10000 |         15000 | 0.5 |        10000 |        25000 |            |
      |        7 | Vroom  |          | 00AA1005 | vrqaauto | ******** |         | 5YJSA1H18EFP57743 |      |       |      | 2014 | 2020-10-08    | 2020-10-08           | Yes              |                       | Pre-Owned        | FINANCE     |     2000 | VROOM EVEHICLE VSC PROTECTION        |                 | PLATINUM COVERAGE                    |   72 |     85000 |        100 |                      |                      |                  |       1720 |        2740 | No               |               | TESTQA007 | TESTQA107 | 123 STREET |      90013 |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |       10000 |         15000 | 0.5 |        10000 |        25000 |            |

  @SubmitContract_Vroom_PROD
  Scenario Outline: Save and Submit the New Contract
    Given Go to url with data as "<TestCase>" and "<Portal>" and "<Language>"and "<Dealer>"
    And Login as "<UserName>" and "<Password>" and "<Captcha>"
    When Click on add New eContract
    And Decode the VIN "<Vin>"
    And Enter contract purchase information "<Vin>" and "<Trim>" and "<Inservicedate>" and "<ContractPurchaseDate>" and "<Vehicle_Purchase>" and "<Vehicle_Purchase_Date>" and "<Vehicle_condtion>" and "<FinanceType>" and "<odometer>" and "<Province>"
    And Select product and get rates "<SelectProduct>" and "<BundleSelection>" and "<Plan>" and "<Term>" and "<TermMiles>" and "<Deductible>" and "<RetailPrice>" and "<DealerCost>" and "<FirstServiceInterval>" and "<FinalServiceInterval>" and "<RegistrationCode>"
    And Verify Dealer Cost and Retail Price "<DealerCost>" and "<RetailPrice>"
    And Enter customer details "<isThisaBussiness>" and "<customerAgreementLanguage>" and "<BussinessName>" and "<FirstName>" and "<LastName>" and "<Address>" and "<PostalCode>" and "<PhoneNumber1>" and "<EmailAddress>" and "<Co-Signer>" and "<cos-First Name>" and "<cos-Last Name>" and "<cos-Address>" and "<cos-Postal Code>" and "<cos-Phone Number 1>" and "<cos-Email Address>" and "<SelectProduct>"
    And Enter vehicle purchase price and finance info "<SelectProduct>" and "<VehicleMSRP>" and "<FinanceAmount>" and  "<APR>" and "<GrossCapCost>" and "<Vehicleprice>"
    And Select Lienholder "<Lienholder>" and "<SelectProduct>"
    And Save the contract
    And Go to the summary page
    And Click on Manage Saved eContracts
    And Select the contract with Last Name "<LastName>", VIN "<Vin>", Product "<SelectProduct>" and Portal "<Portal>"
    And Submit the contract
    Then Logout out from the portal

    Examples: 
      | TestCase | Portal | Language | Dealer   | UserName | Password | Captcha | Vin               | Make | Model | Trim | Year | Inservicedate | ContractPurchaseDate | Vehicle_Purchase | Vehicle_Purchase_Date | Vehicle_condtion | FinanceType | odometer | SelectProduct                        | BundleSelection | Plan                                 | Term | TermMiles | Deductible | FirstServiceInterval | FinalServiceInterval | RegistrationCode | DealerCost | RetailPrice | isThisaBussiness | BussinessName | FirstName | LastName  | Address    | PostalCode | PhoneNumber1 | EmailAddress  | Co-Signer | cos-FirstName | cos-LastName | cos-Address | cos-PostalCode | cos-PhoneNumber1 | cos-EmailAddress | VehicleMSRP | FinanceAmount | APR | GrossCapCost | Vehicleprice | Lienholder |
      |        1 | Vroom  |          | 00AA1005 | vrqaauto | ******** |         | 3VW447AU2HM031522 |      |       |      | 2016 | 2020-10-08    | 2020-10-08           | Yes              |                       | Pre-Owned        | FINANCE     |     2000 | VROOM VSC PROTECTION                 |                 | PLATINUM COVERAGE                    |   48 |    100000 |        100 |                      |                      |                  |       1028 |        1374 | No               |               | TESTQA001 | TESTQA101 | 123 STREET |      90013 |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |       10000 |         15000 | 0.5 |        10000 |        25000 |            |
      |        2 | Vroom  |          | 00AA1005 | vrqaauto | ******** |         | 3VW167AJ2GM282775 |      |       |      | 2016 | 2020-10-08    | 2020-10-08           | Yes              |                       | Pre-Owned        | FINANCE     |     2000 | VROOM GAP PROTECTION                 |                 | VROOM GAP PROTECTION                 |   84 |           |          0 |                      |                      |                  |        233 |         300 | No               |               | TESTQA002 | TESTQA102 | 123 STREET |      90013 |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |       10000 |         15000 | 0.5 |        10000 |        25000 |            |
      |        3 | Vroom  |          | 00AA1005 | vrqaauto | ******** |         | 3VW167AJ2GM244866 |      |       |      | 2016 | 2020-10-08    | 2020-10-08           | Yes              |                       | Pre-Owned        | FINANCE     |     2000 | VROOM ROADSIDE PROTECTION            |                 | VROOM ROADSIDE PROTECTION            |   12 |           |          0 |                      |                      |                  |         18 |          28 | No               |               | TESTQA003 | TESTQA103 | 123 STREET |      90013 |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |       10000 |         15000 | 0.5 |        10000 |        25000 |            |
      |        4 | Vroom  |          | 00AA1005 | vrqaauto | ******** |         | WBA6D6C53GGF53733 |      |       |      | 2016 | 2020-10-08    | 2020-10-08           | Yes              |                       | Pre-Owned        | FINANCE     |     2000 | VROOM SPECIALTY PARTNER LTD WARRANTY |                 | VROOM SPECIALTY PARTNER LTD WARRANTY |    6 |     10000 |         50 |                      |                      |                  |        175 |         200 | No               |               | TESTQA004 | TESTQA104 | 123 STREET |      90013 |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |       10000 |         15000 | 0.5 |        10000 |        25000 |            |
      |        5 | Vroom  |          | 00AA1005 | vrqaauto | ******** |         | WAU57LFF4G1025712 |      |       |      | 2016 | 2020-10-08    | 2020-10-08           | Yes              |                       | Pre-Owned        | FINANCE     |     2000 | VROOM TIRE AND WHEEL PROTECTION      |                 | VROOM TIRE AND WHEEL PROTECTION      |   12 |           |          0 |                      |                      |                  |        231 |         100 | No               |               | TESTQA005 | TESTQA105 | 123 STREET |      90013 |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |       10000 |         15000 | 0.5 |        10000 |        25000 |            |
      |        6 | Vroom  |          | 00AA1005 | vrqaauto | ******** |         | WVWKP7AU1HW146969 |      |       |      | 2016 | 2020-10-08    | 2020-10-08           | Yes              |                       | Pre-Owned        | FINANCE     |     2000 | VROOM VSC LIMITED WARRANTY           |                 | VROOM VSC LIMITED PROTECTION         |    3 |      6000 |         50 |                      |                      |                  |        100 |         120 | No               |               | TESTQA006 | TESTQA106 | 123 STREET |      90013 |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |       10000 |         15000 | 0.5 |        10000 |        25000 |            |
      |        7 | Vroom  |          | 00AA1005 | vrqaauto | ******** |         | 5YJSA1H18EFP57743 |      |       |      | 2014 | 2020-10-08    |                      | Yes              |                       | Pre-Owned        | FINANCE     |     2000 | VROOM EVEHICLE VSC PROTECTION        |                 | PLATINUM COVERAGE                    |   72 |     85000 |        100 |                      |                      |                  |       1720 |        2740 | No               |               | TESTQA007 | TESTQA107 | 123 STREET |      90013 |   9999999999 | test@test.com | No        |               |              |             |                |                  |                  |       10000 |         15000 | 0.5 |        10000 |        25000 |            |
